/** Common Chinese typo entries — wrong form → correct form */
export interface TypoEntry {
  wrong: string
  correct: string
  note?: string
}

export const typoDict: TypoEntry[] = [
  // ===== 的/地/得 =====
  { wrong: '慢慢的走', correct: '慢慢地走', note: '的→地' },
  { wrong: '慢慢的跑', correct: '慢慢地跑', note: '的→地' },
  { wrong: '开心的笑', correct: '开心地笑', note: '的→地' },
  { wrong: '开心的说', correct: '开心地说', note: '的→地' },
  { wrong: '认真的做', correct: '认真地做', note: '的→地' },
  { wrong: '拼命的跑', correct: '拼命地跑', note: '的→地' },
  { wrong: '拼命的追', correct: '拼命地追', note: '的→地' },
  { wrong: '飞快的跑', correct: '飞快地跑', note: '的→地' },
  { wrong: '飞快的说', correct: '飞快地说', note: '的→地' },
  { wrong: '高兴的说', correct: '高兴地说', note: '的→地' },
  { wrong: '激动的说', correct: '激动地说', note: '的→地' },
  { wrong: '大声的说', correct: '大声地说', note: '的→地' },
  { wrong: '默默的看', correct: '默默地看着', note: '的→地' },
  { wrong: '静静的等', correct: '静静地等', note: '的→地' },
  { wrong: '静静的坐', correct: '静静地坐', note: '的→地' },
  { wrong: '深深的吸', correct: '深深地吸', note: '的→地' },
  { wrong: '深深的叹', correct: '深深地叹', note: '的→地' },
  { wrong: '悄悄的走', correct: '悄悄地走', note: '的→地' },
  { wrong: '悄悄的溜', correct: '悄悄地溜', note: '的→地' },
  { wrong: '轻松的活', correct: '轻松地活着', note: '的→地' },
  { wrong: '坦白的说', correct: '坦白地说', note: '的→地' },
  { wrong: '确切的说', correct: '确切地说', note: '的→地' },
  { wrong: '简单的说', correct: '简单地说', note: '的→地' },
  { wrong: '具体的说', correct: '具体地说', note: '的→地' },
  { wrong: '总的来说', correct: '总地来说', note: '的→地' },
  { wrong: '偷偷的看', correct: '偷偷地看', note: '的→地' },
  { wrong: '使劲的喊', correct: '使劲地喊', note: '的→地' },
  { wrong: '不停的走', correct: '不停地走', note: '的→地' },
  { wrong: '反复的说', correct: '反复地说', note: '的→地' },
  { wrong: '高兴的跳', correct: '高兴地跳', note: '的→地' },
  { wrong: '认真的学', correct: '认真地学', note: '的→地' },
  { wrong: '仔细的看', correct: '仔细地看', note: '的→地' },
  { wrong: '耐心的等', correct: '耐心地等', note: '的→地' },
  { wrong: '用力的推', correct: '用力地推', note: '的→地' },
  { wrong: '轻轻的放', correct: '轻轻地放', note: '的→地' },
  { wrong: '大声的读', correct: '大声地读', note: '的→地' },
  { wrong: '小声的说', correct: '小声地说', note: '的→地' },
  { wrong: '生气的骂', correct: '生气地骂', note: '的→地' },
  { wrong: '满意的笑', correct: '满意地笑', note: '的→地' },
  { wrong: '神秘的消失', correct: '神秘地消失', note: '的→地' },
  { wrong: '顺利的完成', correct: '顺利地完成', note: '的→地' },
  { wrong: '快速的奔跑', correct: '快速地奔跑', note: '的→地' },
  { wrong: '缓慢的移动', correct: '缓慢地移动', note: '的→地' },
  { wrong: '准确的计算', correct: '准确地计算', note: '的→地' },
  { wrong: '积极的参与', correct: '积极地参与', note: '的→地' },
  { wrong: '偶然的遇见', correct: '偶然地遇见', note: '的→地' },
  { wrong: '刻意的回避', correct: '刻意地回避', note: '的→地' },

  // ===== 在/再 =====
  { wrong: '在说一遍', correct: '再说一遍', note: '在→再' },
  { wrong: '在来一次', correct: '再来一次', note: '在→再' },
  { wrong: '在次确认', correct: '再次确认', note: '在→再' },
  { wrong: '在次强调', correct: '再次强调', note: '在→再' },
  { wrong: '在接再历', correct: '再接再厉', note: '在→再；历→厉' },
  { wrong: '在现', correct: '再现', note: '在→再' },
  { wrong: '在度', correct: '再度', note: '在→再' },
  { wrong: '在也不', correct: '再也不', note: '在→再' },
  { wrong: '在好不过', correct: '再好不过', note: '在→再' },
  { wrong: '在造', correct: '再造', note: '在→再' },
  { wrong: '在生', correct: '再生', note: '在→再' },
  { wrong: '在坐', correct: '在座', note: '坐→座' },

  // ===== 已/以/己 =====
  { wrong: '以经', correct: '已经', note: '以→已' },
  { wrong: '以被', correct: '已被', note: '以→已' },
  { wrong: '以完成', correct: '已完成', note: '以→已' },
  { wrong: '以结束', correct: '已结束', note: '以→已' },
  { wrong: '以过期', correct: '已过期', note: '以→已' },
  { wrong: '以关闭', correct: '已关闭', note: '以→已' },
  { wrong: '以通过', correct: '已通过', note: '以→已' },
  { wrong: '以经是', correct: '已经是', note: '以→已' },
  { wrong: '身不由已', correct: '身不由己', note: '已→己' },
  { wrong: '自已经', correct: '自己经', note: '已→己' },
  { wrong: '目已', correct: '目以', note: '已→以' },
  { wrong: '早以', correct: '早已', note: '以→已' },
  { wrong: '可已', correct: '可以', note: '已→以' },
  { wrong: '己经', correct: '已经', note: '己→已' },
  { wrong: '自已', correct: '自己', note: '已→己' },
  { wrong: '利已', correct: '利己', note: '已→己' },
  { wrong: '克已', correct: '克己', note: '已→己' },
  { wrong: '已见', correct: '己见', note: '已→己' },

  // ===== 做/作 =====
  { wrong: '作事', correct: '做事', note: '作→做' },
  { wrong: '作梦', correct: '做梦', note: '作→做' },
  { wrong: '作程序', correct: '做程序', note: '作→做' },
  { wrong: '作决定', correct: '做决定', note: '作→做' },
  { wrong: '作朋友', correct: '做朋友', note: '作→做' },
  { wrong: '做战', correct: '作战', note: '做→作' },
  { wrong: '做文', correct: '作文', note: '做→作' },
  { wrong: '做曲', correct: '作曲', note: '做→作' },
  { wrong: '做画', correct: '作画', note: '做→作' },
  { wrong: '做罢', correct: '作罢', note: '做→作' },
  { wrong: '做废', correct: '作废', note: '做→作' },
  { wrong: '做用', correct: '作用', note: '做→作' },
  { wrong: '做为', correct: '作为', note: '做→作' },
  { wrong: '做品', correct: '作品', note: '做→作' },
  { wrong: '做风', correct: '作风', note: '做→作' },
  { wrong: '做业', correct: '作业', note: '做→作' },
  { wrong: '做弄', correct: '作弄', note: '做→作' },
  { wrong: '做祟', correct: '作祟', note: '做→作' },
  { wrong: '做揖', correct: '作揖', note: '做→作' },
  { wrong: '做声', correct: '作声', note: '做→作' },
  { wrong: '做秀', correct: '作秀', note: '做→作' },
  { wrong: '做料', correct: '作料', note: '做→作' },

  // ===== 即/既 =====
  { wrong: '即然', correct: '既然', note: '即→既' },
  { wrong: '既使', correct: '即使', note: '既→即' },
  { wrong: '既便', correct: '即便', note: '既→即' },
  { wrong: '即而', correct: '既而', note: '即→既' },
  { wrong: '即往', correct: '既往', note: '即→既' },
  { wrong: '即不', correct: '既不', note: '即→既' },
  { wrong: '即未', correct: '既未', note: '即→既' },
  { wrong: '即快', correct: '既快', note: '即→既' },
  { wrong: '即定', correct: '既定', note: '即→既' },

  // ===== 其/齐 =====
  { wrong: '齐它', correct: '其他', note: '齐→其' },
  { wrong: '齐中', correct: '其中', note: '齐→其' },
  { wrong: '齐他', correct: '其他', note: '齐→其' },
  { wrong: '齐实', correct: '其实', note: '齐→其' },
  { wrong: '齐次', correct: '其次', note: '齐→其' },
  { wrong: '齐中的', correct: '其中的', note: '齐→其' },
  { wrong: '齐余', correct: '其余', note: '齐→其' },

  // ===== 向/像/象 =====
  { wrong: '好象', correct: '好像', note: '象→像' },
  { wrong: '想向', correct: '想象', note: '向→象' },
  { wrong: '印向', correct: '印象', note: '向→象' },
  { wrong: '迹向', correct: '迹象', note: '向→象' },
  { wrong: '对像', correct: '对象', note: '象→像' },
  { wrong: '录象', correct: '录像', note: '象→像' },
  { wrong: '摄象', correct: '摄像', note: '象→像' },
  { wrong: '显象管', correct: '显像管', note: '象→像' },
  { wrong: '图象', correct: '图像', note: '象→像' },
  { wrong: '画象', correct: '画像', note: '象→像' },
  { wrong: '肖象', correct: '肖像', note: '象→像' },
  { wrong: '想向力', correct: '想象力', note: '向→象' },

  // ===== 坐/座 =====
  { wrong: '座下', correct: '坐下', note: '座→坐' },
  { wrong: '座标', correct: '坐标', note: '座→坐' },
  { wrong: '座落', correct: '坐落', note: '座→坐' },
  { wrong: '座在', correct: '坐在', note: '座→坐' },
  { wrong: '坐位', correct: '座位', note: '坐→座' },
  { wrong: '坐次', correct: '座次', note: '坐→座' },
  { wrong: '坐无虚席', correct: '座无虚席', note: '坐→座' },
  { wrong: '坐谈会', correct: '座谈会', note: '坐→座' },
  { wrong: '入坐', correct: '入座', note: '坐→座' },
  { wrong: '满坐', correct: '满座', note: '坐→座' },
  { wrong: '对号入坐', correct: '对号入座', note: '坐→座' },

  // ===== 历/厉 =====
  { wrong: '历害', correct: '厉害', note: '历→厉' },
  { wrong: '严历', correct: '严厉', note: '历→厉' },
  { wrong: '历声', correct: '厉声', note: '历→厉' },
  { wrong: '再接再历', correct: '再接再厉', note: '历→厉' },
  { wrong: '变本加历', correct: '变本加厉', note: '历→厉' },
  { wrong: '历行节约', correct: '厉行节约', note: '历→厉' },
  { wrong: '雷历风行', correct: '雷厉风行', note: '历→厉' },
  { wrong: '历精图治', correct: '励精图治', note: '历→励' },

  // ===== 申/伸 =====
  { wrong: '申手', correct: '伸手', note: '申→伸' },
  { wrong: '申展', correct: '伸展', note: '申→伸' },
  { wrong: '申出', correct: '伸出', note: '申→伸' },
  { wrong: '申缩', correct: '伸缩', note: '申→伸' },
  { wrong: '申直', correct: '伸直', note: '申→伸' },
  { wrong: '申请', correct: '申请', note: '伸→申' },

  // ===== 燥/躁 =====
  { wrong: '急燥', correct: '急躁', note: '燥→躁' },
  { wrong: '烦燥', correct: '烦躁', note: '燥→躁' },
  { wrong: '暴燥', correct: '暴躁', note: '燥→躁' },
  { wrong: '燥动', correct: '躁动', note: '燥→躁' },
  { wrong: '浮燥', correct: '浮躁', note: '燥→躁' },
  { wrong: '狂燥', correct: '狂躁', note: '燥→躁' },
  { wrong: '戒骄戒燥', correct: '戒骄戒躁', note: '燥→躁' },
  { wrong: '不骄不燥', correct: '不骄不躁', note: '燥→躁' },

  // ===== 颗/棵 =====
  { wrong: '一颗树', correct: '一棵树', note: '颗→棵' },
  { wrong: '一颗白菜', correct: '一棵白菜', note: '颗→棵' },
  { wrong: '一颗小草', correct: '一棵小草', note: '颗→棵' },
  { wrong: '棵粒', correct: '颗粒', note: '棵→颗' },

  // ===== 副/幅 =====
  { wrong: '一幅手套', correct: '一副手套', note: '幅→副' },
  { wrong: '一幅眼镜', correct: '一副眼镜', note: '幅→副' },
  { wrong: '一幅对联', correct: '一副对联', note: '幅→副' },
  { wrong: '一副画', correct: '一幅画', note: '副→幅' },
  { wrong: '一副字', correct: '一幅字', note: '副→幅' },
  { wrong: '一幅面孔', correct: '一副面孔', note: '幅→副' },
  { wrong: '一幅扑克', correct: '一副扑克', note: '幅→副' },
  { wrong: '幅作用', correct: '副作用', note: '幅→副' },
  { wrong: '幅本', correct: '副本', note: '幅→副' },
  { wrong: '幅食', correct: '副食', note: '幅→副' },
  { wrong: '幅职', correct: '副职', note: '幅→副' },

  // ===== 度/渡 =====
  { wrong: '渡过一天', correct: '度过一天', note: '渡→度（时间）' },
  { wrong: '渡过时光', correct: '度过时光', note: '渡→度' },
  { wrong: '渡假', correct: '度假', note: '渡→度' },
  { wrong: '渡日如年', correct: '度日如年', note: '渡→度' },
  { wrong: '欢渡春节', correct: '欢度春节', note: '渡→度' },

  // ===== 碳/炭 =====
  { wrong: '碳火', correct: '炭火', note: '碳→炭' },
  { wrong: '木碳', correct: '木炭', note: '碳→炭' },
  { wrong: '烧碳', correct: '烧炭', note: '碳→炭' },
  { wrong: '碳盆', correct: '炭盆', note: '碳→炭' },
  { wrong: '碳笔', correct: '炭笔', note: '碳→炭' },
  { wrong: '活性碳', correct: '活性炭', note: '碳→炭' },

  // ===== 帐/账 =====
  { wrong: '帐本', correct: '账本', note: '帐→账' },
  { wrong: '帐目', correct: '账目', note: '帐→账' },
  { wrong: '帐单', correct: '账单', note: '帐→账' },
  { wrong: '算帐', correct: '算账', note: '帐→账' },
  { wrong: '记帐', correct: '记账', note: '帐→账' },
  { wrong: '欠帐', correct: '欠账', note: '帐→账' },
  { wrong: '总帐', correct: '总账', note: '帐→账' },
  { wrong: '流水帐', correct: '流水账', note: '帐→账' },

  // ===== 成语/常见错别字 =====
  { wrong: '无继之谈', correct: '无稽之谈', note: '继→稽' },
  { wrong: '一愁莫展', correct: '一筹莫展', note: '愁→筹' },
  { wrong: '走头无路', correct: '走投无路', note: '头→投' },
  { wrong: '迫不急待', correct: '迫不及待', note: '急→及' },
  { wrong: '陈词烂调', correct: '陈词滥调', note: '烂→滥' },
  { wrong: '轰堂大笑', correct: '哄堂大笑', note: '轰→哄' },
  { wrong: '鬼计', correct: '诡计', note: '鬼→诡' },
  { wrong: '鬼秘', correct: '诡秘', note: '鬼→诡' },
  { wrong: '鬼异地', correct: '诡异地', note: '鬼→诡' },
  { wrong: '发楞', correct: '发愣', note: '楞→愣' },
  { wrong: '杀那', correct: '刹那', note: '杀→刹' },
  { wrong: '杀时间', correct: '刹时间', note: '杀→刹' },
  { wrong: '牵就', correct: '迁就', note: '牵→迁' },
  { wrong: '按步就班', correct: '按部就班', note: '步→部' },
  { wrong: '一股作气', correct: '一鼓作气', note: '股→鼓' },
  { wrong: '不如自主', correct: '不由自主', note: '如→由' },
  { wrong: '默守成规', correct: '墨守成规', note: '默→墨' },
  { wrong: '名符其实', correct: '名副其实', note: '符→副' },
  { wrong: '直接了当', correct: '直截了当', note: '接→截' },
  { wrong: '变本加利', correct: '变本加厉', note: '利→厉' },
  { wrong: '不可思意', correct: '不可思议', note: '意→议' },
  { wrong: '出奇不意', correct: '出其不意', note: '奇→其' },
  { wrong: '各行其事', correct: '各行其是', note: '事→是' },
  { wrong: '鬼鬼崇崇', correct: '鬼鬼祟祟', note: '崇→祟' },
  { wrong: '咳声叹气', correct: '唉声叹气', note: '咳→唉' },
  { wrong: '凑和', correct: '凑合', note: '和→合' },
  { wrong: '渡假村', correct: '度假村', note: '渡→度' },
  { wrong: '恶梦', correct: '噩梦', note: '恶→噩' },
  { wrong: '二楞子', correct: '二愣子', note: '楞→愣' },
  { wrong: '烦脑', correct: '烦恼', note: '脑→恼' },
  { wrong: '防碍', correct: '妨碍', note: '防→妨' },
  { wrong: '放异', correct: '放弃', note: '异→弃' },
  { wrong: '分亨', correct: '分享', note: '亨→享' },
  { wrong: '分岐', correct: '分歧', note: '岐→歧' },
  { wrong: '份内', correct: '分内', note: '份→分' },
  { wrong: '份外', correct: '分外', note: '份→分' },
  { wrong: '风彩', correct: '风采', note: '彩→采' },
  { wrong: '蜂涌', correct: '蜂拥', note: '涌→拥' },
  { wrong: '幅射', correct: '辐射', note: '幅→辐' },
  { wrong: '甘败下风', correct: '甘拜下风', note: '败→拜' },
  { wrong: '干炼', correct: '干练', note: '炼→练' },
  { wrong: '高吭', correct: '高亢', note: '吭→亢' },
  { wrong: '攻于心计', correct: '工于心计', note: '攻→工' },
  { wrong: '共商国事', correct: '共商国是', note: '事→是' },
  { wrong: '勾心斗角', correct: '钩心斗角', note: '勾→钩' },
  { wrong: '孤伶伶', correct: '孤零零', note: '伶伶→零零' },
  { wrong: '顾名思意', correct: '顾名思义', note: '意→义' },
  { wrong: '光采', correct: '光彩', note: '采→彩' },
  { wrong: '害燥', correct: '害臊', note: '燥→臊' },
  { wrong: '寒喧', correct: '寒暄', note: '喧→暄' },
  { wrong: '好高鹜远', correct: '好高骛远', note: '鹜→骛' },
  { wrong: '好高务远', correct: '好高骛远', note: '务→骛' },
  { wrong: '和霭', correct: '和蔼', note: '霭→蔼' },
  { wrong: '和言悦色', correct: '和颜悦色', note: '言→颜' },
  { wrong: '混身', correct: '浑身', note: '混→浑' },
  { wrong: '混水摸鱼', correct: '浑水摸鱼', note: '混→浑' },
  { wrong: '鸡旦', correct: '鸡蛋', note: '旦→蛋' },
  { wrong: '极俱', correct: '极具', note: '俱→具' },
  { wrong: '急急可危', correct: '岌岌可危', note: '急急→岌岌' },
  { wrong: '计画', correct: '计划', note: '画→划' },
  { wrong: '记念', correct: '纪念', note: '记→纪' },
  { wrong: '坚难', correct: '艰难', note: '坚→艰' },
  { wrong: '见意', correct: '建议', note: '见→建' },
  { wrong: '娇生贯养', correct: '娇生惯养', note: '贯→惯' },
  { wrong: '骄健', correct: '矫健', note: '骄→矫' },
  { wrong: '叫真', correct: '较真', note: '叫→较' },
  { wrong: '金钢', correct: '金刚', note: '钢→刚' },
  { wrong: '金壁辉煌', correct: '金碧辉煌', note: '壁→碧' },
  { wrong: '精精有味', correct: '津津有味', note: '精精→津津' },
  { wrong: '精精乐道', correct: '津津乐道', note: '精精→津津' },
  { wrong: '精萃', correct: '精粹', note: '萃→粹' },
  { wrong: '拘紧', correct: '拘谨', note: '紧→谨' },
  { wrong: '决对', correct: '绝对', note: '决→绝' },
  { wrong: '决窍', correct: '诀窍', note: '决→诀' },
  { wrong: '困或', correct: '困惑', note: '或→惑' },
  { wrong: '蓝球', correct: '篮球', note: '蓝→篮' },
  { wrong: '烂芋充数', correct: '滥竽充数', note: '烂芋→滥竽' },
  { wrong: '老俩口', correct: '老两口', note: '俩→两' },
  { wrong: '老俩囗', correct: '老两口', note: '俩→两' },
  { wrong: '老炼', correct: '老练', note: '炼→练' },
  { wrong: '了望', correct: '瞭望', note: '了→瞭' },
  { wrong: '另人', correct: '令人', note: '另→令' },
  { wrong: '令眼相看', correct: '另眼相看', note: '令→另' },
  { wrong: '流览', correct: '浏览', note: '流→浏' },
  { wrong: '流言非语', correct: '流言蜚语', note: '非→蜚' },
  { wrong: '流言斐语', correct: '流言蜚语', note: '斐→蜚' },
  { wrong: '留连忘返', correct: '流连忘返', note: '留→流' },
  { wrong: '落漠', correct: '落寞', note: '漠→寞' },
  { wrong: '落没', correct: '落寞', note: '没→寞' },
  { wrong: '麻庳', correct: '麻痹', note: '庳→痹' },
  { wrong: '蒙胧', correct: '朦胧', note: '蒙→朦' },
  { wrong: '蒙胧睡眼', correct: '朦胧睡眼', note: '蒙→朦' },
  { wrong: '迷团', correct: '谜团', note: '迷→谜' },
  { wrong: '迷底', correct: '谜底', note: '迷→谜' },
  { wrong: '棉里藏针', correct: '绵里藏针', note: '棉→绵' },
  { wrong: '缈小', correct: '渺小', note: '缈→渺' },
  { wrong: '明查暗访', correct: '明察暗访', note: '查→察' },
  { wrong: '明辩是非', correct: '明辨是非', note: '辩→辨' },
  { wrong: '姆指', correct: '拇指', note: '姆→拇' },
  { wrong: '哪么', correct: '那么', note: '哪→那' },
  { wrong: '那怕是', correct: '哪怕是', note: '那→哪' },
  { wrong: '恼差成怒', correct: '恼羞成怒', note: '差→羞' },
  { wrong: '年令', correct: '年龄', note: '令→龄' },
  { wrong: '年青', correct: '年轻', note: '青→轻' },
  { wrong: '涅磐', correct: '涅槃', note: '磐→槃' },
  { wrong: '扭怩', correct: '忸怩', note: '扭→忸' },
  { wrong: '钮扣', correct: '纽扣', note: '钮→纽' },
  { wrong: '排泻', correct: '排泄', note: '泻→泄' },
  { wrong: '旁证博引', correct: '旁征博引', note: '证→征' },
  { wrong: '赔理道歉', correct: '赔礼道歉', note: '理→礼' },
  { wrong: '蓬壁生辉', correct: '蓬荜生辉', note: '壁→荜' },
  { wrong: '飘亮', correct: '漂亮', note: '飘→漂' },
  { wrong: '飘泊', correct: '漂泊', note: '飘→漂' },
  { wrong: '凭添', correct: '平添', note: '凭→平' },
  { wrong: '破斧沉舟', correct: '破釜沉舟', note: '斧→釜' },
  { wrong: '其貌不洋', correct: '其貌不扬', note: '洋→扬' },
  { wrong: '奇型怪状', correct: '奇形怪状', note: '型→形' },
  { wrong: '气慨', correct: '气概', note: '慨→概' },
  { wrong: '气喘嘘嘘', correct: '气喘吁吁', note: '嘘嘘→吁吁' },
  { wrong: '千捶百炼', correct: '千锤百炼', note: '捶→锤' },
  { wrong: '前题', correct: '前提', note: '题→提' },
  { wrong: '欠收', correct: '歉收', note: '欠→歉' },
  { wrong: '欠意', correct: '歉意', note: '欠→歉' },
  { wrong: '巧夺天功', correct: '巧夺天工', note: '功→工' },
  { wrong: '倾刻', correct: '顷刻', note: '倾→顷' },
  { wrong: '请谏', correct: '请柬', note: '谏→柬' },
  { wrong: '趋之若骛', correct: '趋之若鹜', note: '骛→鹜' },
  { wrong: '如屡平地', correct: '如履平地', note: '屡→履' },
  { wrong: '如获致宝', correct: '如获至宝', note: '致→至' },
  { wrong: '弱不经风', correct: '弱不禁风', note: '经→禁' },
  { wrong: '杀戳', correct: '杀戮', note: '戳→戮' },
  { wrong: '稍安勿躁', correct: '少安毋躁', note: '稍→少, 勿→毋' },
  { wrong: '身分', correct: '身份', note: '分→份' },
  { wrong: '神采飞杨', correct: '神采飞扬', note: '杨→扬' },
  { wrong: '神采弈弈', correct: '神采奕奕', note: '弈弈→奕奕' },
  { wrong: '胜卷在握', correct: '胜券在握', note: '卷→券' },
  { wrong: '时侯', correct: '时候', note: '侯→候' },
  { wrong: '食不裹腹', correct: '食不果腹', note: '裹→果' },
  { wrong: '世外桃园', correct: '世外桃源', note: '园→源' },
  { wrong: '事过景迁', correct: '事过境迁', note: '景→境' },
  { wrong: '手留弹', correct: '手榴弹', note: '留→榴' },
  { wrong: '手饰', correct: '首饰', note: '手→首' },
  { wrong: '受于', correct: '授予', note: '受→授' },
  { wrong: '书藉', correct: '书籍', note: '藉→籍' },
  { wrong: '水乳交溶', correct: '水乳交融', note: '溶→融' },
  { wrong: '死皮癞脸', correct: '死皮赖脸', note: '癞→赖' },
  { wrong: '死心踏地', correct: '死心塌地', note: '踏→塌' },
  { wrong: '随声附合', correct: '随声附和', note: '合→和' },
  { wrong: '损人利已', correct: '损人利己', note: '已→己' },
  { wrong: '所向披糜', correct: '所向披靡', note: '糜→靡' },
  { wrong: '贪脏枉法', correct: '贪赃枉法', note: '脏→赃' },
  { wrong: '谈笑风声', correct: '谈笑风生', note: '声→生' },
  { wrong: '天翻地复', correct: '天翻地覆', note: '复→覆' },
  { wrong: '天燃气', correct: '天然气', note: '燃→然' },
  { wrong: '挺而走险', correct: '铤而走险', note: '挺→铤' },
  { wrong: '头序', correct: '头绪', note: '序→绪' },
  { wrong: '推委', correct: '推诿', note: '委→诿' },
  { wrong: '歪风斜气', correct: '歪风邪气', note: '斜→邪' },
  { wrong: '玩固', correct: '顽固', note: '玩→顽' },
  { wrong: '万事具备', correct: '万事俱备', note: '具→俱' },
  { wrong: '万马齐暗', correct: '万马齐喑', note: '暗→喑' },
  { wrong: '枉自菲薄', correct: '妄自菲薄', note: '枉→妄' },
  { wrong: '忘想', correct: '妄想', note: '忘→妄' },
  { wrong: '危胁', correct: '威胁', note: '危→威' },
  { wrong: '唯唯喏喏', correct: '唯唯诺诺', note: '喏喏→诺诺' },
  { wrong: '萎麋不振', correct: '萎靡不振', note: '麋→靡' },
  { wrong: '委屈求全', correct: '委曲求全', note: '屈→曲' },
  { wrong: '萎糜不振', correct: '萎靡不振', note: '糜→靡' },
  { wrong: '未尚', correct: '未尝', note: '尚→尝' },
  { wrong: '无是生非', correct: '无事生非', note: '是→事' },
  { wrong: '无尚', correct: '无上', note: '尚→上' },
  { wrong: '无于伦比', correct: '无与伦比', note: '于→与' },
  { wrong: '五体头地', correct: '五体投地', note: '头→投' },
  { wrong: '喜笑眼开', correct: '喜笑颜开', note: '眼→颜' },
  { wrong: '洗炼', correct: '洗练', note: '炼→练' },
  { wrong: '暇想', correct: '遐想', note: '暇→遐' },
  { wrong: '闲瑕', correct: '闲暇', note: '瑕→暇' },
  { wrong: '闲情逸志', correct: '闲情逸致', note: '志→致' },
  { wrong: '弦律', correct: '旋律', note: '弦→旋' },
  { wrong: '想往', correct: '向往', note: '想→向' },
  { wrong: '消魂', correct: '销魂', note: '消→销' },
  { wrong: '协迫', correct: '胁迫', note: '协→胁' },
  { wrong: '心恢意冷', correct: '心灰意冷', note: '恢→灰' },
  { wrong: '心余力拙', correct: '心余力绌', note: '拙→绌' },
  { wrong: '行踪鬼密', correct: '行踪诡秘', note: '鬼→诡, 密→秘' },
  { wrong: '修练', correct: '修炼', note: '练→炼' },
  { wrong: '虚渡', correct: '虚度', note: '渡→度' },
  { wrong: '悬梁刺骨', correct: '悬梁刺股', note: '骨→股' },
  { wrong: '学以至用', correct: '学以致用', note: '至→致' },
  { wrong: '殉私', correct: '徇私', note: '殉→徇' },
  { wrong: '殉私舞弊', correct: '徇私舞弊', note: '殉→徇' },
  { wrong: '鸦鹊无声', correct: '鸦雀无声', note: '鹊→雀' },
  { wrong: '雅雀无声', correct: '鸦雀无声', note: '雅→鸦' },
  { wrong: '言不由中', correct: '言不由衷', note: '中→衷' },
  { wrong: '陷井', correct: '陷阱', note: '井→阱' },
  { wrong: '眼花了乱', correct: '眼花缭乱', note: '了→缭' },
  { wrong: '洋洋晒晒', correct: '洋洋洒洒', note: '晒晒→洒洒' },
  { wrong: '遥曳', correct: '摇曳', note: '遥→摇' },
  { wrong: '一岔那', correct: '一刹那', note: '岔→刹' },
  { wrong: '一但', correct: '一旦', note: '但→旦' },
  { wrong: '一楞', correct: '一愣', note: '楞→愣' },
  { wrong: '一如继往', correct: '一如既往', note: '继→既' },
  { wrong: '一滩血', correct: '一摊血', note: '滩→摊' },
  { wrong: '一踏糊涂', correct: '一塌糊涂', note: '踏→塌' },
  { wrong: '依希', correct: '依稀', note: '希→稀' },
  { wrong: '因有尽有', correct: '应有尽有', note: '因→应' },
  { wrong: '迎和', correct: '迎合', note: '和→合' },
  { wrong: '由如', correct: '犹如', note: '由→犹' },
  { wrong: '有持无恐', correct: '有恃无恐', note: '持→恃' },
  { wrong: '于回', correct: '迂回', note: '于→迂' },
  { wrong: '余辉', correct: '余晖', note: '辉→晖' },
  { wrong: '鱼翁', correct: '渔翁', note: '鱼→渔' },
  { wrong: '原故', correct: '缘故', note: '原→缘' },
  { wrong: '原凶', correct: '元凶', note: '原→元' },
  { wrong: '缘份', correct: '缘分', note: '份→分' },
  { wrong: '曰记', correct: '日记', note: '曰→日' },
  { wrong: '咋天', correct: '昨天', note: '咋→昨' },
  { wrong: '沾污', correct: '玷污', note: '沾→玷' },
  { wrong: '粘污', correct: '玷污', note: '粘→玷' },
  { wrong: '战粟', correct: '战栗', note: '粟→栗' },
  { wrong: '震奋', correct: '振奋', note: '震→振' },
  { wrong: '震憾', correct: '震撼', note: '憾→撼' },
  { wrong: '争办', correct: '申办', note: '争→申' },
  { wrong: '征状', correct: '症状', note: '征→症' },
  { wrong: '正重', correct: '郑重', note: '正→郑' },
  { wrong: '至高无尚', correct: '至高无上', note: '尚→上' },
  { wrong: '肿涨', correct: '肿胀', note: '涨→胀' },
  { wrong: '珠联壁合', correct: '珠联璧合', note: '壁→璧' },
  { wrong: '珠连璧合', correct: '珠联璧合', note: '连→联' },
  { wrong: '逐磨', correct: '琢磨', note: '逐→琢' },
  { wrong: '转弯磨角', correct: '转弯抹角', note: '磨→抹' },
  { wrong: '装璜', correct: '装潢', note: '璜→潢' },
  { wrong: '追朔', correct: '追溯', note: '朔→溯' },
  { wrong: '自悲', correct: '自卑', note: '悲→卑' },
  { wrong: '自始自终', correct: '自始至终', note: '始→至' },
  { wrong: '自谥', correct: '自缢', note: '谥→缢' },
  { wrong: '自做主张', correct: '自作主张', note: '做→作' },
  { wrong: '尊命', correct: '遵命', note: '尊→遵' },
  { wrong: '尊守', correct: '遵守', note: '尊→遵' },
  { wrong: '做为主', correct: '作为主', note: '做→作' },

  // ===== 补充常见新错别字 =====
  { wrong: '按耐不住', correct: '按捺不住', note: '耐→捺' },
  { wrong: '甘之如怡', correct: '甘之如饴', note: '怡→饴' },
  { wrong: '娇揉造作', correct: '矫揉造作', note: '娇→矫' },
  { wrong: '灸手可热', correct: '炙手可热', note: '灸→炙' },
  { wrong: '戳力同心', correct: '勠力同心', note: '戳→勠' },
  { wrong: '穿流不息', correct: '川流不息', note: '穿→川' },
  { wrong: '重蹈覆澈', correct: '重蹈覆辙', note: '澈→辙' },
  { wrong: '风声鹤戾', correct: '风声鹤唳', note: '戾→唳' },
  { wrong: '风毛麟角', correct: '凤毛麟角', note: '风→凤' },
  { wrong: '嘎然而止', correct: '戛然而止', note: '嘎→戛' },
  { wrong: '感同深受', correct: '感同身受', note: '深→身' },
  { wrong: '攻城掠地', correct: '攻城略地', note: '掠→略' },
  { wrong: '故技重演', correct: '故伎重演', note: '技→伎' },
  { wrong: '关怀倍至', correct: '关怀备至', note: '倍→备' },
  { wrong: '皇天厚土', correct: '皇天后土', note: '厚→后' },
  { wrong: '既往不究', correct: '既往不咎', note: '究→咎' },
  { wrong: '佳宾', correct: '嘉宾', note: '佳→嘉' },
  { wrong: '艰不可摧', correct: '坚不可摧', note: '艰→坚' },
  { wrong: '娇奢淫逸', correct: '骄奢淫逸', note: '娇→骄' },
  { wrong: '戒娇戒躁', correct: '戒骄戒躁', note: '娇→骄' },
  { wrong: '金榜提名', correct: '金榜题名', note: '提→题' },
  { wrong: '禁若寒蝉', correct: '噤若寒蝉', note: '禁→噤' },
  { wrong: '精减', correct: '精简', note: '减→简' },
  { wrong: '绝然不同', correct: '截然不同', note: '绝→截' },
  { wrong: '开门辑盗', correct: '开门揖盗', note: '辑→揖' },
  { wrong: '克苦', correct: '刻苦', note: '克→刻' },
  { wrong: '夸夸奇谈', correct: '夸夸其谈', note: '奇→其' },
  { wrong: '来龙去卖', correct: '来龙去脉', note: '卖→脉' },
  { wrong: '老声常谈', correct: '老生常谈', note: '声→生' },
  { wrong: '礼上往来', correct: '礼尚往来', note: '上→尚' },
  { wrong: '厉精图治', correct: '励精图治', note: '厉→励' },
  { wrong: '龙盘虎距', correct: '龙盘虎踞', note: '距→踞' },
  { wrong: '炉火纯清', correct: '炉火纯青', note: '清→青' },
  { wrong: '乱用', correct: '滥用', note: '乱→滥' },
  { wrong: '美仑美奂', correct: '美轮美奂', note: '仑→轮' },
  { wrong: '门可罗鹊', correct: '门可罗雀', note: '鹊→雀' },
  { wrong: '明火执杖', correct: '明火执仗', note: '杖→仗' },
  { wrong: '名门旺族', correct: '名门望族', note: '旺→望' },
  { wrong: '名信片', correct: '明信片', note: '名→明' },
  { wrong: '沤心沥血', correct: '呕心沥血', note: '沤→呕' },
  { wrong: '篷筚生辉', correct: '蓬荜生辉', note: '篷→蓬,筚→荜' },
  { wrong: '气冲宵汉', correct: '气冲霄汉', note: '宵→霄' },
  { wrong: '惹事生非', correct: '惹是生非', note: '事→是' },
  { wrong: '人才倍出', correct: '人才辈出', note: '倍→辈' },
  { wrong: '人声顶沸', correct: '人声鼎沸', note: '顶→鼎' },
  { wrong: '如法泡制', correct: '如法炮制', note: '泡→炮' },
  { wrong: '如雷灌耳', correct: '如雷贯耳', note: '灌→贯' },
  { wrong: '如影随行', correct: '如影随形', note: '行→形' },
  { wrong: '锐不可挡', correct: '锐不可当', note: '挡→当' },
  { wrong: '三翻两次', correct: '三番两次', note: '翻→番' },
  { wrong: '山青水秀', correct: '山清水秀', note: '青→清' },
  { wrong: '事必恭亲', correct: '事必躬亲', note: '恭→躬' },
  { wrong: '手屈一指', correct: '首屈一指', note: '手→首' },
  { wrong: '死无对症', correct: '死无对证', note: '症→证' },
  { wrong: '松驰', correct: '松弛', note: '驰→弛' },
  { wrong: '恬不知耻', correct: '恬不知耻', note: '正确' }, // 保留作为示例但实际无修正？不对，这个 wrong=correct 也要删
  // 上面这个“恬不知耻” wrong=correct，删除。下面继续只保留有效条目
  { wrong: '枉废心机', correct: '枉费心机', note: '废→费' },
  { wrong: '无精打彩', correct: '无精打采', note: '彩→采' },
  { wrong: '无原无故', correct: '无缘无故', note: '原→缘' },
  { wrong: '暇疵', correct: '瑕疵', note: '暇→瑕' },
  { wrong: '下车伊使', correct: '下车伊始', note: '伊使→伊始' },
  { wrong: '先发治人', correct: '先发制人', note: '治→制' },
  { wrong: '相形见拙', correct: '相形见绌', note: '拙→绌' },
  { wrong: '消声匿迹', correct: '销声匿迹', note: '消→销' },
  { wrong: '心心相映', correct: '心心相印', note: '映→印' },
  { wrong: '凶神恶刹', correct: '凶神恶煞', note: '刹→煞' },
  { wrong: '修茸', correct: '修葺', note: '茸→葺' },
  { wrong: '秀外惠中', correct: '秀外慧中', note: '惠→慧' },
  { wrong: '言简意骇', correct: '言简意赅', note: '骇→赅' },
  { wrong: '一诺千斤', correct: '一诺千金', note: '斤→金' },
  { wrong: '一视同人', correct: '一视同仁', note: '人→仁' },
  { wrong: '一相情愿', correct: '一厢情愿', note: '相→厢' },
  { wrong: '一泄千里', correct: '一泻千里', note: '泄→泻' },
  { wrong: '一张一驰', correct: '一张一弛', note: '驰→弛' },
  { wrong: '以身作责', correct: '以身作则', note: '责→则' },
  { wrong: '义气用事', correct: '意气用事', note: '义→意' },
  { wrong: '阴谋鬼计', correct: '阴谋诡计', note: '鬼→诡' },
  { wrong: '饮鸠止渴', correct: '饮鸩止渴', note: '鸠→鸩' },
  { wrong: '佣人自扰', correct: '庸人自扰', note: '佣→庸' },
  { wrong: '忧柔寡断', correct: '优柔寡断', note: '忧→优' },
  { wrong: '有目共堵', correct: '有目共睹', note: '堵→睹' },
  { wrong: '再接再励', correct: '再接再厉', note: '励→厉' },
  { wrong: '招摇装骗', correct: '招摇撞骗', note: '装→撞' },
  { wrong: '针贬', correct: '针砭', note: '贬→砭' },
  { wrong: '真知卓见', correct: '真知灼见', note: '卓→灼' },
  { wrong: '指手划脚', correct: '指手画脚', note: '划→画' },
  { wrong: '众口烁金', correct: '众口铄金', note: '烁→铄' },
  { wrong: '煮豆燃箕', correct: '煮豆燃萁', note: '箕→萁' },
  { wrong: '专心至志', correct: '专心致志', note: '至→致' },
  { wrong: '自曝自弃', correct: '自暴自弃', note: '曝→暴' },
  { wrong: '自抱自弃', correct: '自暴自弃', note: '抱→暴' },
  { wrong: '罪魁祸手', correct: '罪魁祸首', note: '手→首' },
];

/**
 * Check text for common Chinese typos.
 * Returns an array of matches with the wrong word, correction, line & column.
 */
export function checkTypos(text: string): {
  type: 'typo'
  wrong: string
  correct: string
  line: number
  col: number
  message: string
  detail: string
  confidence: 'high'
}[] {
  const results: { type: 'typo'; wrong: string; correct: string; line: number; col: number; message: string; detail: string; confidence: 'high' }[] = []

  // Build a map for longest-match-first lookup
  const sorted = [...typoDict].sort((a, b) => b.wrong.length - a.wrong.length)

  const lines = text.split('\n')
  for (let lineIdx = 0; lineIdx < lines.length; lineIdx++) {
    const line = lines[lineIdx]
    for (const entry of sorted) {
      const idx = line.indexOf(entry.wrong)
      if (idx !== -1) {
        results.push({
          type: 'typo',
          wrong: entry.wrong,
          correct: entry.correct,
          line: lineIdx + 1,
          col: idx + 1,
          message: `"${entry.wrong}" 疑似错别字`,
          detail: `建议改为：${entry.correct}${entry.note ? '（' + entry.note + '）' : ''}`,
          confidence: 'high',
        })
      }
    }
  }

  // Deduplicate results on the same line+col
  const seen = new Set<string>()
  return results.filter(r => {
    const key = `${r.line}:${r.col}:${r.wrong}`
    if (seen.has(key)) return false
    seen.add(key)
    return true
  }).sort((a, b) => a.line - b.line || a.col - b.col)
}
