import type { TemplateItem } from '../types'

export const id = 'bg'
export const name = '背景卡片'
export const icon = '🎴'

export const templates: TemplateItem[] = [
  {
    id: 'bg-1',
    name: '紫蓝渐变卡片',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:linear-gradient(135deg,#667eea,#764ba2); border-radius:12px; text-align:center;"><p style="margin:0; font-size:18px; font-weight:bold; color:#fff;">重点内容</p><p style="margin:8px 0 0; font-size:13px; color:rgba(255,255,255,.85);">清晰美观的渐变高亮内容</p></div>',
  },
  {
    id: 'bg-2',
    name: '樱花粉渐变',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:linear-gradient(135deg,#f093fb,#f5576c); border-radius:12px; text-align:center; color:#fff;"><p style="margin:0; font-size:16px; font-weight:bold;">🌸 温柔粉色内容</p><p style="margin:8px 0 0; font-size:13px; opacity:.9;">适合生活、情感、女性内容</p></div>',
  },
  {
    id: 'bg-3',
    name: '深色商务卡片',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:20px; background:#2c3e50; border-radius:10px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#ecf0f1;">深色商务内容</p><p style="margin:8px 0 0; font-size:12px; color:#bdc3c7;">正式、科技、专业场景</p></div>',
  },
  {
    id: 'bg-4',
    name: '清新薄荷绿',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#e6f7f0; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#27ae60;">清新治愈内容</p><p style="margin:8px 0 0; font-size:13px; color:#555;">护眼柔和，适合长文阅读</p></div>',
  },
  {
    id: 'bg-5',
    name: '暖橙活力',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#fff4e5; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#ff7d00;">活力温馨提示</p><p style="margin:8px 0 0; font-size:13px; color:#774d1f;">适合公告、注意事项、重点提醒</p></div>',
  },
  {
    id: 'bg-6',
    name: '天空淡蓝',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#e8f4ff; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#3498db;">清爽简洁内容</p><p style="margin:8px 0 0; font-size:13px; color:#444;">通用百搭，适合各类正文</p></div>',
  },
  {
    id: 'bg-7',
    name: '轻奢香槟金',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:linear-gradient(135deg,#fdfbf4,#f5ecd6); border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#b88642;">轻奢质感内容</p><p style="margin:8px 0 0; font-size:13px; color:#7a5b2e;">适合干货、精品、成长内容</p></div>',
  },
  {
    id: 'bg-8',
    name: '科技青黑',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#1f2937; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#10b981;">科技暗黑风格</p><p style="margin:8px 0 0; font-size:13px; color:#9ca3af;">IT、技术、教程类内容</p></div>',
  },
  {
    id: 'bg-9',
    name: '温柔香芋紫',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#f4f0ff; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#8c7aea;">温柔文艺内容</p><p style="margin:8px 0 0; font-size:13px; color:#666;">美文、随笔、情感内容</p></div>',
  },
  {
    id: 'bg-10',
    name: '中国红喜庆',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#fef2f2; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#e53e3e;">红色重点强调</p><p style="margin:8px 0 0; font-size:13px; color:#742323;">适合重点、通知、活动</p></div>',
  },
  {
    id: 'bg-11',
    name: '灰调高级感',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#f7f8fa; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#444;">高级简约灰色</p><p style="margin:8px 0 0; font-size:13px; color:#888;">商务、极简、干净风格</p></div>',
  },
  {
    id: 'bg-12',
    name: '青绿国风',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#edf7f2; border-radius:8px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#3c7d75;">国风雅致内容</p><p style="margin:8px 0 0; font-size:13px; color:#555;">诗词、文化、传统内容</p></div>',
  },
  {
    id: 'bg-13',
    name: '霓虹蓝紫',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:linear-gradient(135deg,#3a1c71,#d76d77); border-radius:12px; text-align:center; color:#fff;"><p style="margin:0; font-size:16px; font-weight:bold;">霓虹潮流风格</p><p style="margin:8px 0 0; font-size:13px; opacity:.9;">年轻、时尚、潮流内容</p></div>',
  },
  {
    id: 'bg-14',
    name: '柔雾玫瑰',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#fff5f7; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#d48a9e;">柔雾玫瑰风格</p><p style="margin:8px 0 0; font-size:13px; color:#775560;">美妆、穿搭、生活内容</p></div>',
  },
  {
    id: 'bg-15',
    name: '深海静谧蓝',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#eef5ff; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#2563eb;">深海静谧风格</p><p style="margin:8px 0 0; font-size:13px; color:#334155;">职场、学习、成长内容</p></div>',
  },
  {
    id: 'bg-16',
    name: '立体阴影卡片',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:#fff; border-radius:12px; box-shadow:0 4px 12px rgba(0,0,0,0.08); text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#333;">立体悬浮卡片</p><p style="margin:8px 0 0; font-size:13px; color:#777;">通用高级，超实用</p></div>',
  },
  {
    id: 'bg-17',
    name: '活力青柠',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#f0ffe0; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#7cb342;">活力青柠风格</p><p style="margin:8px 0 0; font-size:13px; color:#4a6c2c;">健康、运动、日常内容</p></div>',
  },
  {
    id: 'bg-18',
    name: '复古焦糖',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#fbf3e9; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#ab6831;">复古焦糖风格</p><p style="margin:8px 0 0; font-size:13px; color:#7a4b22;">文艺、美食、手作内容</p></div>',
  },
  {
    id: 'bg-19',
    name: '极光渐变',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:linear-gradient(135deg,#4facfe,#00f2fe); border-radius:12px; text-align:center; color:#fff;"><p style="margin:0; font-size:16px; font-weight:bold;">极光清新渐变</p><p style="margin:8px 0 0; font-size:13px; opacity:.95;">科技、旅行、创意内容</p></div>',
  },
  {
    id: 'bg-20',
    name: '极简纯白卡片',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#fff; border:1px solid #eee; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#333;">极简纯白卡片</p><p style="margin:8px 0 0; font-size:13px; color:#888;">干净、通用、高级</p></div>',
  },
  {
    id: 'bg-21',
    name: '暗紫神秘',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#2a1d36; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#e4c1ff;">暗紫神秘风格</p><p style="margin:8px 0 0; font-size:13px; color:#b794d6;">影视、星座、心理内容</p></div>',
  },
  {
    id: 'bg-22',
    name: '暖棕大地',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#f8f5f0; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#8b6a4d;">暖棕大地风格</p><p style="margin:8px 0 0; font-size:13px; color:#6d523c;">家居、生活、读书内容</p></div>',
  },
  {
    id: 'bg-23',
    name: '荧光珊瑚',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#ffe8e6; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#ff6b6b;">荧光珊瑚风格</p><p style="margin:8px 0 0; font-size:13px; color:#9f4141;">少女、日常、种草内容</p></div>',
  },
  {
    id: 'bg-24',
    name: '商务深蓝',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#eff6ff; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#1d4ed8;">商务深蓝风格</p><p style="margin:8px 0 0; font-size:13px; color:#3b4252;">报告、职场、正式内容</p></div>',
  },
  {
    id: 'bg-25',
    name: '水墨国风灰',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#f7f6f3; border-radius:8px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#555;">水墨国风简约</p><p style="margin:8px 0 0; font-size:13px; color:#777;">书法、古文、文化内容</p></div>',
  },
  {
    id: 'bg-26',
    name: '草莓奶冻',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#fff0f4; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#e86a92;">草莓奶冻风格</p><p style="margin:8px 0 0; font-size:13px; color:#9c5069;">可爱、萌系、日常内容</p></div>',
  },
  {
    id: 'bg-27',
    name: '森林墨绿',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#e6f4ea; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#0f766e;">森林墨绿风格</p><p style="margin:8px 0 0; font-size:13px; color:#375241;">自然、治愈、成长内容</p></div>',
  },
  {
    id: 'bg-28',
    name: '落日晚霞',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:linear-gradient(135deg,#fa709a,#fee140); border-radius:12px; text-align:center; color:#fff;"><p style="margin:0; font-size:16px; font-weight:bold;">落日晚霞渐变</p><p style="margin:8px 0 0; font-size:13px; opacity:.95;">情感、旅行、治愈内容</p></div>',
  },
  {
    id: 'bg-29',
    name: '磨砂质感灰',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#f1f2f6; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#444;">磨砂质感卡片</p><p style="margin:8px 0 0; font-size:13px; color:#777;">极简、高级、商务内容</p></div>',
  },
  {
    id: 'bg-30',
    name: '薰衣草淡紫',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#f8f4ff; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#7c3aed;">薰衣草淡紫</p><p style="margin:8px 0 0; font-size:13px; color:#555;">梦幻、文艺、情感内容</p></div>',
  },
  {
    id: 'bg-31',
    name: '黑金高级',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:linear-gradient(135deg,#242424,#3a3a3a); border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#f9d342;">黑金轻奢风格</p><p style="margin:8px 0 0; font-size:13px; color:#ccc;">高端、品质、干货内容</p></div>',
  },
  {
    id: 'bg-32',
    name: '海盐芝士',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#fcf8ee; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#d4a66f;">海盐芝士风格</p><p style="margin:8px 0 0; font-size:13px; color:#8a6a46;">美食、下午茶、生活内容</p></div>',
  },
  {
    id: 'bg-33',
    name: '冰爽冰川蓝',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#e0f7fa; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#00acc1;">冰爽冰川蓝</p><p style="margin:8px 0 0; font-size:13px; color:#006064;">夏季、清凉、科技内容</p></div>',
  },
  {
    id: 'bg-34',
    name: '豆沙温柔',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#f5ebe8; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#b87a72;">豆沙温柔风格</p><p style="margin:8px 0 0; font-size:13px; color:#7d534e;">美妆、穿搭、文艺内容</p></div>',
  },
  {
    id: 'bg-35',
    name: '电竞赛博',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:linear-gradient(135deg,#0f0f23,#1a1a2e); border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#4adec7;">电竞赛博风格</p><p style="margin:8px 0 0; font-size:13px; color:#aaa;">游戏、科技、数码内容</p></div>',
  },
  {
    id: 'bg-36',
    name: '奶白柔光',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#fffbf5; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#b89075;">奶白柔光风格</p><p style="margin:8px 0 0; font-size:13px; color:#8a6a54;">母婴、育儿、日常内容</p></div>',
  },
  {
    id: 'bg-37',
    name: '青绿薄荷',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#e8f5e9; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#43a047;">青绿薄荷风格</p><p style="margin:8px 0 0; font-size:13px; color:#336935;">护眼、学习、办公内容</p></div>',
  },
  {
    id: 'bg-38',
    name: '玫瑰鎏金',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:linear-gradient(135deg,#b86b8c,#d4a5b9); border-radius:12px; text-align:center; color:#fff;"><p style="margin:0; font-size:16px; font-weight:bold;">玫瑰鎏金风格</p><p style="margin:8px 0 0; font-size:13px; opacity:.95;">轻奢、女性、精致内容</p></div>',
  },
  {
    id: 'bg-39',
    name: '水泥工业灰',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#e0e0e0; border-radius:8px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#424242;">水泥工业风格</p><p style="margin:8px 0 0; font-size:13px; color:#616161;">男士、职场、极简内容</p></div>',
  },
  {
    id: 'bg-40',
    name: '淡粉云朵',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#fceaff; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#ce93d8;">淡粉云朵风格</p><p style="margin:8px 0 0; font-size:13px; color:#8a6da6;">可爱、少女、治愈内容</p></div>',
  },
  {
    id: 'bg-41',
    name: '海军深蓝',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#172b4d; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#fff;">海军深蓝风格</p><p style="margin:8px 0 0; font-size:13px; color:#bdc3c7;">正式、商务、报告内容</p></div>',
  },
  {
    id: 'bg-42',
    name: '芒果甜橙',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#fff3e0; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#ff9800;">芒果甜橙风格</p><p style="margin:8px 0 0; font-size:13px; color:#e65100;">美食、活力、日常内容</p></div>',
  },
  {
    id: 'bg-43',
    name: '玉石青',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#e0f2f1; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#26a69a;">玉石青风格</p><p style="margin:8px 0 0; font-size:13px; color:#00796b;">国风、禅意、文化内容</p></div>',
  },
  {
    id: 'bg-44',
    name: '樱花雾粉',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:linear-gradient(135deg,#ffccee,#ffddee); border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#c2185b;">樱花雾粉渐变</p><p style="margin:8px 0 0; font-size:13px; color:#880e4f;">少女、浪漫、生活内容</p></div>',
  },
  {
    id: 'bg-45',
    name: '炭黑极简',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#121212; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#fff;">炭黑极简风格</p><p style="margin:8px 0 0; font-size:13px; color:#aaa;">高级、科技、男士内容</p></div>',
  },
  {
    id: 'bg-46',
    name: '亚麻米色',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#faf6f0; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#9c7f5c;">亚麻米色风格</p><p style="margin:8px 0 0; font-size:13px; color:#7c6549;">日系、文艺、手作内容</p></div>',
  },
  {
    id: 'bg-47',
    name: '电光蓝',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:linear-gradient(135deg,#007adf,#00ecbc); border-radius:12px; text-align:center; color:#fff;"><p style="margin:0; font-size:16px; font-weight:bold;">电光蓝科技感</p><p style="margin:8px 0 0; font-size:13px; opacity:.95;">数码、IT、教程内容</p></div>',
  },
  {
    id: 'bg-48',
    name: '蜜桃乌龙',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#ffe8e8; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#e57373;">蜜桃乌龙风格</p><p style="margin:8px 0 0; font-size:13px; color:#9c4444;">美食、生活、种草内容</p></div>',
  },
  {
    id: 'bg-49',
    name: '雾灰商务',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:22px; background:#f4f7fa; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#4e596f;">雾灰商务风格</p><p style="margin:8px 0 0; font-size:13px; color:#777;">办公、职场、报告内容</p></div>',
  },
  {
    id: 'bg-50',
    name: '纯白金边卡片',
    category: 'bg',
    html: '<div style="margin:20px 0; padding:24px; background:#fff; border:1px solid #e6d2b5; border-radius:12px; text-align:center;"><p style="margin:0; font-size:16px; font-weight:bold; color:#b88946;">纯白金边轻奢</p><p style="margin:8px 0 0; font-size:13px; color:#8a6d3b;">精品、干货、正式内容</p></div>',
  }
]
