import type { TemplateItem } from '../types'

export const id = 'body'
export const name = '正文'
export const icon = '📝'

export const templates: TemplateItem[] = [
  {
    id: 'body-1',
    name: '正文段落',
    category: 'body',
    html: '<p style="margin: 12px 0; font-size: 15px; line-height: 1.8; color: #444; text-indent: 2em;">这里是正文内容。微信公众号文章的正文字号建议使用 15px-16px，行高 1.8 左右，这样在手机上阅读体验最佳。</p>',
  },
  {
    id: 'body-2',
    name: '引用框',
    category: 'body',
    html: '<blockquote style="margin: 15px 0; padding: 12px 16px; background: #f5f7fa; border-left: 4px solid #4a7dd4; border-radius: 0 6px 6px 0; color: #666; font-size: 14px; line-height: 1.7;">这是一个引用样式的正文块，适合用来强调某句话或引用某段文字。</blockquote>',
  },
  {
    id: 'body-3',
    name: '背景框正文',
    category: 'body',
    html: '<div style="margin: 15px 0; padding: 16px 18px; background: #f0f4f9; border-radius: 8px; font-size: 14px; line-height: 1.8; color: #444;"><p style="margin: 0; text-indent: 2em;">带灰色背景的正文块，适合需要突出显示的内容段落，与纯白背景形成视觉区分。</p></div>',
  },
  {
    id: 'body-4',
    name: '提示条',
    category: 'body',
    html: '<div style="margin: 15px 0; padding: 10px 14px; display: flex; align-items: flex-start; gap: 8px; background: #fff8e1; border-radius: 6px; border-left: 4px solid #ffc107;"><span style="font-size: 16px; flex-shrink: 0;">💡</span><p style="margin: 0; font-size: 13px; color: #8a7a4a; line-height: 1.6;">温馨提示：这里是提示性文字内容。</p></div>',
  },
  {
    id: 'body-5',
    name: '双栏列表',
    category: 'body',
    html: '<div style="display: flex; gap: 16px; margin: 15px 0;"><div style="flex: 1; padding: 12px; background: #e8f0fe; border-radius: 8px; text-align: center;"><p style="margin: 0; font-size: 13px; color: #4a7dd4; font-weight: bold;">特点一</p></div><div style="flex: 1; padding: 12px; background: #e8f0fe; border-radius: 8px; text-align: center;"><p style="margin: 0; font-size: 13px; color: #4a7dd4; font-weight: bold;">特点二</p></div></div>',
  },
  {
    id: 'body-6',
    name: '无缩进清爽正文',
    category: 'body',
    html: '<p style="margin:10px 0; font-size:15px; line-height:1.8; color:#333;">正文内容无需缩进，更适合资讯、干货、教程类文章排版，阅读更轻松。</p>',
  },
  {
    id: 'body-7',
    name: '红色重点高亮正文',
    category: 'body',
    html: '<p style="margin:12px 0; font-size:15px; line-height:1.8; color:#e53e3e; font-weight:bold;">重点强调文字，用于关键结论、注意事项、核心内容。</p>',
  },
  {
    id: 'body-8',
    name: '绿色安全提示框',
    category: 'body',
    html: '<div style="margin:15px 0; padding:12px 14px; background:#f0fdf4; border-left:4px solid #10b981; border-radius:0 6px 6px 0;"><p style="margin:0; font-size:14px; color:#065f46; line-height:1.7;">成功/完成/正确类提示内容，清晰醒目。</p></div>',
  },
  {
    id: 'body-9',
    name: '蓝色信息引用框',
    category: 'body',
    html: '<div style="margin:15px 0; padding:14px; background:#eff6ff; border-radius:8px;"><p style="margin:0; font-size:14px; color:#1e40af; line-height:1.8;">说明、补充、解释类正文，适合专业内容排版。</p></div>',
  },
  {
    id: 'body-10',
    name: '橙色警告提示条',
    category: 'body',
    html: '<div style="margin:15px 0; padding:10px 14px; display:flex; align-items:center; gap:8px; background:#fff7ed; border-radius:6px;"><span style="font-size:16px;">⚠️</span><p style="margin:0; font-size:14px; color:#c2410c; line-height:1.6;">警告：重要注意事项，必须提醒用户留意。</p></div>',
  },
  {
    id: 'body-11',
    name: '紫色文艺正文',
    category: 'body',
    html: '<p style="margin:12px 0; font-size:15px; line-height:1.8; color:#7c3aed; text-indent:2em;">温柔文艺风格正文，适合情感、散文、随笔类内容。</p>',
  },
  {
    id: 'body-12',
    name: '三栏小标签布局',
    category: 'body',
    html: '<div style="display:flex; gap:10px; margin:16px 0;"><div style="flex:1; padding:10px; background:#f0f9ff; border-radius:8px; text-align:center;"><p style="margin:0; font-size:13px; color:#0369a1;">标签一</p></div><div style="flex:1; padding:10px; background:#f0f9ff; border-radius:8px; text-align:center;"><p style="margin:0; font-size:13px; color:#0369a1;">标签二</p></div><div style="flex:1; padding:10px; background:#f0f9ff; border-radius:8px; text-align:center;"><p style="margin:0; font-size:13px; color:#0369a1;">标签三</p></div></div>',
  },
  {
    id: 'body-13',
    name: '灰色小字备注',
    category: 'body',
    html: '<p style="margin:8px 0; font-size:12px; line-height:1.6; color:#9ca3af;">备注说明：小字灰色，用于注释、来源、补充说明。</p>',
  },
  {
    id: 'body-14',
    name: '深色商务正文块',
    category: 'body',
    html: '<div style="margin:16px 0; padding:16px; background:#1f2937; border-radius:8px;"><p style="margin:0; font-size:14px; line-height:1.8; color:#e5e7eb;">深色商务正文，适合报告、教程、技术类内容。</p></div>',
  },
  {
    id: 'body-15',
    name: '爱心粉色温馨正文',
    category: 'body',
    html: '<div style="margin:15px 0; padding:12px; background:#fdf2f8; border-radius:8px;"><p style="margin:0; font-size:14px; color:#be185d; line-height:1.7;">爱心温馨文案，适合生活、情感、祝福类内容。</p></div>',
  },
  {
    id: 'body-16',
    name: '步骤序号正文',
    category: 'body',
    html: '<div style="margin:14px 0; display:flex; align-items:flex-start; gap:10px;"><div style="width:22px; height:22px; background:#4a7dd4; color:#fff; border-radius:50%; display:flex; align-items:center; justify-content:center; font-size:12px; flex-shrink:0;">1</div><p style="margin:0; font-size:15px; line-height:1.8; color:#333;">第一步操作说明内容，清晰易懂。</p></div>',
  },
  {
    id: 'body-17',
    name: '薄荷绿护眼正文',
    category: 'body',
    html: '<p style="margin:12px 0; font-size:15px; line-height:1.8; color:#047857; text-indent:2em;">护眼绿色正文，长时间阅读不累眼。</p>',
  },
  {
    id: 'body-18',
    name: '对话气泡左边',
    category: 'body',
    html: '<div style="margin:12px 0; max-width:85%;"><div style="padding:10px 14px; background:#f3f4f6; border-radius:14px 14px 14px 4px;"><p style="margin:0; font-size:14px; color:#333; line-height:1.6;">对方聊天对话内容样式。</p></div></div>',
  },
  {
    id: 'body-19',
    name: '对话气泡右边',
    category: 'body',
    html: '<div style="margin:12px 0; max-width:85%; margin-left:auto;"><div style="padding:10px 14px; background:#3b82f6; color:#fff; border-radius:14px 14px 4px 14px;"><p style="margin:0; font-size:14px; line-height:1.6;">我的聊天对话内容样式。</p></div></div>',
  },
  {
    id: 'body-20',
    name: '金色轻奢引用',
    category: 'body',
    html: '<blockquote style="margin:16px 0; padding:14px; background:#fefce8; border-left:4px solid #d97706; border-radius:0 6px 6px 0;"><p style="margin:0; font-size:14px; color:#78350f; line-height:1.7;">轻奢金句引用，适合名言、格言、总结。</p></blockquote>',
  },
  {
    id: 'body-21',
    name: '竖线分割正文',
    category: 'body',
    html: '<div style="margin:16px 0; padding-left:12px; border-left:2px solid #d1d5db;"><p style="margin:0; font-size:15px; line-height:1.8; color:#444;">简约竖线分割正文，干净高级。</p></div>',
  },
  {
    id: 'body-22',
    name: '星星高亮短句',
    category: 'body',
    html: '<p style="margin:12px 0; font-size:15px; color:#f59e0b; font-weight:bold; text-align:center;">⭐ 重点短句总结 ⭐</p>',
  },
  {
    id: 'body-23',
    name: '青色科技正文框',
    category: 'body',
    html: '<div style="margin:15px 0; padding:14px; background:#ecfeff; border-radius:8px;"><p style="margin:0; font-size:14px; color:#155e75; line-height:1.8;">科技感青色正文，适合数码、IT内容。</p></div>',
  },
  {
    id: 'body-24',
    name: '问答提问样式',
    category: 'body',
    html: '<div style="margin:16px 0; padding:12px; background:#f0f4ff; border-radius:8px;"><p style="margin:0; font-size:15px; font-weight:bold; color:#3b82f6;">Q：这是一个常见问题？</p></div>',
  },
  {
    id: 'body-25',
    name: '问答回答样式',
    category: 'body',
    html: '<div style="margin:12px 0 20px; padding:12px; background:#f8fafc; border-radius:8px;"><p style="margin:0; font-size:14px; color:#333; line-height:1.8;">A：这是对应的回答内容，清晰明了。</p></div>',
  },
  {
    id: 'body-26',
    name: '虚线边框备注',
    category: 'body',
    html: '<div style="margin:15px 0; padding:12px; border:1px dashed #94a3b8; border-radius:8px;"><p style="margin:0; font-size:14px; color:#475569; line-height:1.7;">虚线边框备注内容，简约不抢眼。</p></div>',
  },
  {
    id: 'body-27',
    name: '大号重点标题正文',
    category: 'body',
    html: '<p style="margin:18px 0 10px; font-size:16px; font-weight:bold; color:#333;">这是段落大标题，用于分段总结。</p>',
  },
  {
    id: 'body-28',
    name: '咖啡棕文艺正文',
    category: 'body',
    html: '<p style="margin:12px 0; font-size:15px; line-height:1.8; color:#78350f; text-indent:2em;">咖啡棕色文艺正文，适合手作、读书、生活内容。</p>',
  },
  {
    id: 'body-29',
    name: '图标列表单行',
    category: 'body',
    html: '<div style="margin:10px 0; display:flex; align-items:center; gap:8px;"><span style="color:#10b981; font-size:16px;">✅</span><p style="margin:0; font-size:14px; color:#333;">列表项内容，简洁整齐。</p></div>',
  },
  {
    id: 'body-30',
    name: '阴影悬浮卡片正文',
    category: 'body',
    html: '<div style="margin:18px 0; padding:16px; background:#fff; border-radius:10px; box-shadow:0 2px 8px rgba(0,0,0,0.08);"><p style="margin:0; font-size:15px; line-height:1.8; color:#444; text-indent:2em;">立体卡片正文，高级质感。</p></div>',
  },
  {
    id: 'body-31',
    name: '粉色萌系提示',
    category: 'body',
    html: '<div style="margin:15px 0; padding:10px 12px; display:flex; align-items:center; gap:8px; background:#fdf2f8; border-radius:6px;"><span>🌸</span><p style="margin:0; font-size:14px; color:#be185d;">温柔可爱的提示内容。</p></div>',
  },
  {
    id: 'body-32',
    name: '居中强调短句',
    category: 'body',
    html: '<p style="margin:16px 0; font-size:15px; font-weight:bold; color:#4a7dd4; text-align:center;">居中排版，适合小标题、总结句。</p>',
  },
  {
    id: 'body-33',
    name: '代码风格正文',
    category: 'body',
    html: '<div style="margin:15px 0; padding:12px; background:#f8fafc; border-radius:6px; font-family:monospace;"><p style="margin:0; font-size:13px; color:#1e293b; line-height:1.6;">代码格式正文，适合教程、命令展示。</p></div>',
  },
  {
    id: 'body-34',
    name: '国风水墨正文',
    category: 'body',
    html: '<p style="margin:12px 0; font-size:15px; line-height:1.9; color:#3f3f46; text-indent:2em; font-family:sans-serif;">国风雅致正文，适合古文、文化、诗词内容。</p>',
  },
  {
    id: 'body-35',
    name: '蓝色边框高亮框',
    category: 'body',
    html: '<div style="margin:16px 0; padding:14px; border:1px solid #3b82f6; border-radius:8px;"><p style="margin:0; font-size:14px; color:#1e40af; line-height:1.7;">蓝色边框高亮，重点内容展示。</p></div>',
  },
  {
    id: 'body-36',
    name: '绿色完成清单',
    category: 'body',
    html: '<div style="margin:10px 0; display:flex; align-items:center; gap:8px;"><span style="font-size:16px; color:#10b981;">☑️</span><p style="margin:0; font-size:14px; color:#333;">已完成事项清单样式。</p></div>',
  },
  {
    id: 'body-37',
    name: '灰色简约引用',
    category: 'body',
    html: '<p style="margin:15px 0; padding-left:14px; font-size:14px; color:#6b7280; line-height:1.7; border-left:2px solid #d1d5db;">简约灰色引用，低调不抢眼。</p>',
  },
  {
    id: 'body-38',
    name: '暖橙小标题正文',
    category: 'body',
    html: '<p style="margin:14px 0 8px; font-size:15px; font-weight:bold; color:#f97316;">橙色小标题，段落分隔。</p>',
  },
  {
    id: 'body-39',
    name: '双行分隔线正文',
    category: 'body',
    html: '<div style="margin:20px 0;"><div style="height:1px; background:#eee;"></div><p style="margin:10px 0; font-size:14px; text-align:center; color:#9ca3af;">分隔线区域说明</p><div style="height:1px; background:#eee;"></div></div>',
  },
  {
    id: 'body-40',
    name: '紫色神秘感正文',
    category: 'body',
    html: '<div style="margin:15px 0; padding:14px; background:#faf5ff; border-radius:8px;"><p style="margin:0; font-size:14px; color:#7e22ce; line-height:1.8;">紫色神秘感正文，适合星座、心理内容。</p></div>',
  },
  {
    id: 'body-41',
    name: '商务粗体正文',
    category: 'body',
    html: '<p style="margin:12px 0; font-size:15px; font-weight:bold; color:#1f2937; line-height:1.8;">商务风粗体正文，正式、专业。</p>',
  },
  {
    id: 'body-42',
    name: '云朵浅蓝背景正文',
    category: 'body',
    html: '<div style="margin:15px 0; padding:14px; background:#f0f9ff; border-radius:12px;"><p style="margin:0; font-size:15px; line-height:1.8; color:#0369a1; text-indent:2em;">浅蓝云朵正文，清爽舒适。</p></div>',
  },
  {
    id: 'body-43',
    name: '红色错误提示',
    category: 'body',
    html: '<div style="margin:15px 0; padding:10px 12px; display:flex; align-items:center; gap:8px; background:#fef2f2; border-radius:6px;"><span>❌</span><p style="margin:0; font-size:14px; color:#dc2626;">错误/禁止/警告类提示。</p></div>',
  },
  {
    id: 'body-44',
    name: '小圆点列表正文',
    category: 'body',
    html: '<div style="margin:10px 0; display:flex; align-items:flex-start; gap:8px;"><span style="margin-top:8px; width:4px; height:4px; background:#4a7dd4; border-radius:50%; flex-shrink:0;"></span><p style="margin:0; font-size:14px; color:#444; line-height:1.7;">小圆点列表项，简约干净。</p></div>',
  },
  {
    id: 'body-45',
    name: '淡绿治愈短句',
    category: 'body',
    html: '<p style="margin:14px 0; font-size:15px; color:#059669; text-align:center;">🌿 治愈系短句排版 🌿</p>',
  },
  {
    id: 'body-46',
    name: '白色卡片金边正文',
    category: 'body',
    html: '<div style="margin:18px 0; padding:16px; background:#fff; border:1px solid #e6d2b5; border-radius:10px;"><p style="margin:0; font-size:15px; line-height:1.8; color:#333; text-indent:2em;">金边轻奢卡片正文，高级感强。</p></div>',
  },
  {
    id: 'body-47',
    name: '黑色加粗强调',
    category: 'body',
    html: '<p style="margin:12px 0; font-size:15px; font-weight:800; color:#000; line-height:1.8;">超粗黑色强调，最抢眼的重点文字。</p>',
  },
  {
    id: 'body-48',
    name: '浅灰低调正文',
    category: 'body',
    html: '<p style="margin:10px 0; font-size:14px; color:#6b7280; line-height:1.7;">浅灰色低调正文，辅助说明文字。</p>',
  },
  {
    id: 'body-49',
    name: '闪电效率提示',
    category: 'body',
    html: '<div style="margin:15px 0; padding:10px 12px; display:flex; align-items:center; gap:8px; background:#fffbeb; border-radius:6px;"><span>⚡</span><p style="margin:0; font-size:14px; color:#d97706;">高效快捷、技巧类提示内容。</p></div>',
  },
  {
    id: 'body-50',
    name: '圆角全包正文卡片',
    category: 'body',
    html: '<div style="margin:16px 0; padding:16px; background:#f8fafc; border-radius:12px;"><p style="margin:0; font-size:15px; line-height:1.8; color:#333; text-indent:2em;">全圆角大卡片正文，通用百搭。</p></div>',
  },
  {
    id: 'body-51',
    name: '书籍图标引言',
    category: 'body',
    html: '<div style="margin:16px 0; display:flex; align-items:center; gap:10px;"><span style="font-size:18px; color:#6b7280;">📖</span><p style="margin:0; font-size:14px; color:#4b5563; line-height:1.7;">书籍引言、名言、摘抄样式。</p></div>',
  },
  {
    id: 'body-52',
    name: '青色细线标题',
    category: 'body',
    html: '<div style="margin:16px 0; padding-bottom:8px; border-bottom:1px solid #5eead4;"><p style="margin:0; font-size:16px; font-weight:bold; color:#14b8a6;">青色下划线小标题。</p></div>',
  },
  {
    id: 'body-53',
    name: '黄色高亮标注',
    category: 'body',
    html: '<p style="margin:12px 0; font-size:15px; line-height:1.8;">这是一段<span style="background:#fef08a; padding:2px 4px; border-radius:4px;">黄色高亮标注</span>正文。</p>',
  },
  {
    id: 'body-54',
    name: '垂直居中图标正文',
    category: 'body',
    html: '<div style="margin:14px 0; display:flex; align-items:center; gap:10px; padding:12px; background:#f0f4f9; border-radius:8px;"><span style="font-size:18px; color:#4a7dd4;">📌</span><p style="margin:0; font-size:14px; color:#333;">定位、总结、核心内容正文。</p></div>',
  },
  {
    id: 'body-55',
    name: '极简纯白卡片正文',
    category: 'body',
    html: '<div style="margin:16px 0; padding:14px; border:1px solid #e2e8f0; border-radius:10px;"><p style="margin:0; font-size:15px; line-height:1.8; color:#444;">极简纯白卡片正文，干净高级。</p></div>',
  }
]
