import type { TemplateItem } from '../types'

export const id = 'divider'
export const name = '分割线'
export const icon = '➖'

export const templates: TemplateItem[] = [
  {
    id: 'divider-1',
    name: '简单横线',
    category: 'divider',
    html: '<hr style="width:100%; border:none; border-top:2px solid #d0d4dd; margin:25px 0;">',
  },
  {
    id: 'divider-2',
    name: '虚线分割',
    category: 'divider',
    html: '<hr style="width:100%; border:none; border-top:2px dashed #bcc0c8; margin:25px 0;">',
  },
  {
    id: 'divider-3',
    name: '装饰花式',
    category: 'divider',
    html: '<div style="text-align:center; margin:25px 0; font-size:16px; color:#b0b4be; letter-spacing:8px;">✦ ✦ ✦</div>',
  },
  {
    id: 'divider-4',
    name: '渐变分割',
    category: 'divider',
    html: '<div style="width:100%; margin:25px 0; height:3px; background:linear-gradient(90deg,transparent,#4a7dd4,transparent);">&nbsp;</div>',
  },
  {
    id: 'divider-5',
    name: '波浪分割',
    category: 'divider',
    html: '<div style="text-align:center; margin:20px 0; font-size:22px; color:#b0b4be;">~ ~ ~</div>',
  },
  {
    id: 'divider-6',
    name: '图案分割',
    category: 'divider',
    html: '<div style="text-align:center; margin:20px 0; font-size:18px; color:#b0b4be;">◇◆◇◆◇</div>',
  },

  // ==================== 以下追加 50 条 ====================
  {
    id: 'divider-7',
    name: '蓝细渐变线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:2px; background:linear-gradient(90deg,transparent,#93c5fd,transparent);">&nbsp;</div>',
  },
  {
    id: 'divider-8',
    name: '紫粉渐变线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:2px; background:linear-gradient(90deg,transparent,#c084fc,transparent);">&nbsp;</div>',
  },
  {
    id: 'divider-9',
    name: '绿柔渐变线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:2px; background:linear-gradient(90deg,transparent,#4ade80,transparent);">&nbsp;</div>',
  },
  {
    id: 'divider-10',
    name: '橙暖渐变线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:2px; background:linear-gradient(90deg,transparent,#fdba74,transparent);">&nbsp;</div>',
  },
  {
    id: 'divider-11',
    name: '红柔渐变线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:2px; background:linear-gradient(90deg,transparent,#f87171,transparent);">&nbsp;</div>',
  },
  {
    id: 'divider-12',
    name: '圆点星星线',
    category: 'divider',
    html: '<div style="text-align:center; margin:24px 0; color:#999; font-size:14px;">⋅ ⋆ ⋅ ⋆ ⋅</div>',
  },
  {
    id: 'divider-13',
    name: '小花装饰线',
    category: 'divider',
    html: '<div style="text-align:center; margin:24px 0; color:#b8bdc6; font-size:18px;">❀ ❀ ❀</div>',
  },
  {
    id: 'divider-14',
    name: '叶子清新线',
    category: 'divider',
    html: '<div style="text-align:center; margin:22px 0; color:#86c9a0; font-size:20px;">🍃 🍃 🍃</div>',
  },
  {
    id: 'divider-15',
    name: '爱心少女线',
    category: 'divider',
    html: '<div style="text-align:center; margin:22px 0; color:#f9a8d4; font-size:18px;">♡ ♡ ♡</div>',
  },
  {
    id: 'divider-16',
    name: '国风祥云线',
    category: 'divider',
    html: '<div style="text-align:center; margin:24px 0; color:#b8c4e0; font-size:18px;">☁️  ☁️  ☁️</div>',
  },
  {
    id: 'divider-17',
    name: '双色粗实线',
    category: 'divider',
    html: '<div style="width:100%; margin:24px 0; height:3px; background:#d1d5db; border-radius:2px;">&nbsp;</div>',
  },
  {
    id: 'divider-18',
    name: '蓝粗渐变线',
    category: 'divider',
    html: '<div style="width:100%; margin:24px 0; height:3px; background:linear-gradient(90deg,#3b82f6,#60a5fa); border-radius:2px;">&nbsp;</div>',
  },
  {
    id: 'divider-19',
    name: '绿粗渐变线',
    category: 'divider',
    html: '<div style="width:100%; margin:24px 0; height:3px; background:linear-gradient(90deg,#10b981,#34d399); border-radius:2px;">&nbsp;</div>',
  },
  {
    id: 'divider-20',
    name: '紫粗渐变线',
    category: 'divider',
    html: '<div style="width:100%; margin:24px 0; height:3px; background:linear-gradient(90deg,#8b5cf6,#a78bfa); border-radius:2px;">&nbsp;</div>',
  },
  {
    id: 'divider-21',
    name: '灰色点线',
    category: 'divider',
    html: '<hr style="width:100%; border:none; border-top:2px dotted #c0c4cc; margin:22px 0;">',
  },
  {
    id: 'divider-22',
    name: '蓝色点线',
    category: 'divider',
    html: '<hr style="width:100%; border:none; border-top:2px dotted #93c5fd; margin:22px 0;">',
  },
  {
    id: 'divider-23',
    name: '绿色点线',
    category: 'divider',
    html: '<hr style="width:100%; border:none; border-top:2px dotted #86efac; margin:22px 0;">',
  },
  {
    id: 'divider-24',
    name: '粉色点线',
    category: 'divider',
    html: '<hr style="width:100%; border:none; border-top:2px dotted #f9a8d4; margin:22px 0;">',
  },
  {
    id: 'divider-25',
    name: '钻石精致线',
    category: 'divider',
    html: '<div style="text-align:center; margin:24px 0; color:#b0b8d4; font-size:16px;">✧ ✧ ✧</div>',
  },
  {
    id: 'divider-26',
    name: '雪花清新线',
    category: 'divider',
    html: '<div style="text-align:center; margin:24px 0; color:#b8c8e8; font-size:18px;">❄ ❄ ❄</div>',
  },
  {
    id: 'divider-27',
    name: '音符文艺线',
    category: 'divider',
    html: '<div style="text-align:center; margin:22px 0; color:#888; font-size:18px;">♪ ♪ ♪</div>',
  },
  {
    id: 'divider-28',
    name: '太阳温暖线',
    category: 'divider',
    html: '<div style="text-align:center; margin:22px 0; color:#fbbf24; font-size:20px;">☀ ☀ ☀</div>',
  },
  {
    id: 'divider-29',
    name: '双层细线',
    category: 'divider',
    html: '<div style="width:100%; margin:24px 0;"><div style="width:100%; height:2px; background:#d1d5db; margin-bottom:5px;">&nbsp;</div><div style="width:100%; height:2px; background:#d1d5db;">&nbsp;</div></div>',
  },
  {
    id: 'divider-30',
    name: '双层蓝线',
    category: 'divider',
    html: '<div style="width:100%; margin:24px 0;"><div style="width:100%; height:2px; background:#bfdbfe; margin-bottom:5px;">&nbsp;</div><div style="width:100%; height:2px; background:#bfdbfe;">&nbsp;</div></div>',
  },
  {
    id: 'divider-31',
    name: '圆角细线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:3px; background:#d1d5db; border-radius:99px;">&nbsp;</div>',
  },
  {
    id: 'divider-32',
    name: '圆角蓝线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:3px; background:#60a5fa; border-radius:99px;">&nbsp;</div>',
  },
  {
    id: 'divider-33',
    name: '圆角紫线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:3px; background:#a78bfa; border-radius:99px;">&nbsp;</div>',
  },
  {
    id: 'divider-34',
    name: '圆角绿线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:3px; background:#4ade80; border-radius:99px;">&nbsp;</div>',
  },
  {
    id: 'divider-35',
    name: '极简短横线',
    category: 'divider',
    html: '<div style="margin:24px auto; width:80px; height:3px; background:#c0c4cc; border-radius:3px;">&nbsp;</div>',
  },
  {
    id: 'divider-36',
    name: '蓝色短横线',
    category: 'divider',
    html: '<div style="margin:24px auto; width:80px; height:3px; background:#60a5fa; border-radius:3px;">&nbsp;</div>',
  },
  {
    id: 'divider-37',
    name: '粉色短横线',
    category: 'divider',
    html: '<div style="margin:24px auto; width:80px; height:3px; background:#f472b6; border-radius:3px;">&nbsp;</div>',
  },
  {
    id: 'divider-38',
    name: '绿色短横线',
    category: 'divider',
    html: '<div style="margin:24px auto; width:80px; height:3px; background:#22c55e; border-radius:3px;">&nbsp;</div>',
  },
  {
    id: 'divider-39',
    name: '星星中间线',
    category: 'divider',
    html: '<div style="display:flex; width:100%; align-items:center; gap:10px; margin:24px 0;"><div style="flex:1; height:2px; background:#d1d5db;">&nbsp;</div><span style="color:#888; font-size:14px;">⭐</span><div style="flex:1; height:2px; background:#d1d5db;">&nbsp;</div></div>',
  },
  {
    id: 'divider-40',
    name: '小花中间线',
    category: 'divider',
    html: '<div style="display:flex; width:100%; align-items:center; gap:10px; margin:24px 0;"><div style="flex:1; height:2px; background:#d1d5db;">&nbsp;</div><span style="color:#888; font-size:16px;">❀</span><div style="flex:1; height:2px; background:#d1d5db;">&nbsp;</div></div>',
  },
  {
    id: 'divider-41',
    name: '爱心中间线',
    category: 'divider',
    html: '<div style="display:flex; width:100%; align-items:center; gap:10px; margin:24px 0;"><div style="flex:1; height:2px; background:#f9a8d4;">&nbsp;</div><span style="color:#f472b6; font-size:18px;">♡</span><div style="flex:1; height:2px; background:#f9a8d4;">&nbsp;</div></div>',
  },
  {
    id: 'divider-42',
    name: '钻石中间线',
    category: 'divider',
    html: '<div style="display:flex; width:100%; align-items:center; gap:10px; margin:24px 0;"><div style="flex:1; height:2px; background:#c7d2fe;">&nbsp;</div><span style="color:#a78bfa; font-size:16px;">✧</span><div style="flex:1; height:2px; background:#c7d2fe;">&nbsp;</div></div>',
  },
  {
    id: 'divider-43',
    name: '阴影细线',
    category: 'divider',
    html: '<div style="width:100%; margin:26px 0; height:2px; background:#e5e7eb; box-shadow:0 1px 3px rgba(0,0,0,0.08);">&nbsp;</div>',
  },
  {
    id: 'divider-44',
    name: '霓虹蓝光线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:3px; background:#00f2fe; border-radius:99px;">&nbsp;</div>',
  },
  {
    id: 'divider-45',
    name: '霓虹紫光线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:3px; background:#ec4899; border-radius:99px;">&nbsp;</div>',
  },
  {
    id: 'divider-46',
    name: '复古风线',
    category: 'divider',
    html: '<div style="text-align:center; margin:24px 0; color:#888; font-size:16px;">┅┅┅┅┅</div>',
  },
  {
    id: 'divider-47',
    name: '科技感虚线',
    category: 'divider',
    html: '<hr style="width:100%; border:none; border-top:2px dashed #60a5fa; margin:22px 0;">',
  },
  {
    id: 'divider-48',
    name: '文艺虚线',
    category: 'divider',
    html: '<hr style="width:100%; border:none; border-top:2px dashed #d8b4fe; margin:22px 0;">',
  },
  {
    id: 'divider-49',
    name: '云朵柔线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:2px; background:linear-gradient(90deg,transparent,#bfdbfe,transparent);">&nbsp;</div>',
  },
  {
    id: 'divider-50',
    name: '轻奢金线',
    category: 'divider',
    html: '<div style="width:100%; margin:24px 0; height:3px; background:linear-gradient(90deg,transparent,#d97706,transparent); border-radius:2px;">&nbsp;</div>',
  },
  {
    id: 'divider-51',
    name: '水墨古风线',
    category: 'divider',
    html: '<div style="width:100%; margin:24px 0; height:2px; background:linear-gradient(90deg,transparent,#78716c,transparent);">&nbsp;</div>',
  },
  {
    id: 'divider-52',
    name: '极简符号线',
    category: 'divider',
    html: '<div style="text-align:center; margin:22px 0; color:#b0b4be; font-size:16px;">⋅⋅⋅⋅⋅⋅⋅⋅</div>',
  },
  {
    id: 'divider-53',
    name: '枫叶文艺线',
    category: 'divider',
    html: '<div style="text-align:center; margin:24px 0; color:#b8967a; font-size:18px;">🍁 🍁 🍁</div>',
  },
  {
    id: 'divider-54',
    name: '彩虹细线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:3px; background:linear-gradient(90deg,#ef4444,#f59e0b,#10b981,#3b82f6,#8b5cf6); border-radius:99px;">&nbsp;</div>',
  },
  {
    id: 'divider-55',
    name: '商务深色线',
    category: 'divider',
    html: '<div style="width:100%; margin:24px 0; height:2px; background:#4b5563;">&nbsp;</div>',
  },
  {
    id: 'divider-56',
    name: '超柔奶昔线',
    category: 'divider',
    html: '<div style="width:100%; margin:22px 0; height:2px; background:linear-gradient(90deg,transparent,#f9a8d4,transparent);">&nbsp;</div>',
  },

]
