import type { TemplateItem } from '../types'

export const id = 'follow'
export const name = '引导关注'
export const icon = '👋'

export const templates: TemplateItem[] = [
  {
    id: 'follow-1',
    name: '蓝字关注',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #888;">- <span style="color: #4a7dd4; cursor: pointer;">点击蓝字关注</span> 获取更多内容 -</p>',
  },
  {
    id: 'follow-2',
    name: '卡片关注',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 20px; background: #f5f7fa; border-radius: 8px; text-align: center;"><p style="margin: 0 0 8px; font-size: 16px; font-weight: bold; color: #333;">📌 喜欢这篇文章吗？</p><p style="margin: 0 0 14px; font-size: 13px; color: #888;">点击下方关注，不错过每一次更新</p><p style="margin: 0;"><a style="display: inline-block; padding: 8px 28px; background: #4a7dd4; color: #fff; border-radius: 20px; text-decoration: none; font-size: 14px;">关注我们</a></p></div>',
  },
  {
    id: 'follow-3',
    name: '简单提示',
    category: 'follow',
    html: '<p style="text-align: center; margin: 15px 0; font-size: 13px; color: #aaa;">↑ 如果喜欢，请点个「<span style="color: #e74c3c;">♥</span> 在看」</p>',
  },
  {
    id: 'follow-4',
    name: '公众号卡片',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; border: 1px solid #e8e8e8; border-radius: 8px; display: flex; align-items: center; gap: 12px;"><div style="width: 50px; height: 50px; background: #4a7dd4; border-radius: 8px; display: flex; align-items: center; justify-content: center; color: #fff; font-size: 20px; flex-shrink: 0;">✎</div><div style="flex: 1;"><p style="margin: 0 0 2px; font-size: 15px; font-weight: bold; color: #333;">写作助手</p><p style="margin: 0; font-size: 12px; color: #999;">分享创作技巧与优质内容</p></div><a style="padding: 6px 16px; background: #4a7dd4; color: #fff; border-radius: 14px; text-decoration: none; font-size: 12px; flex-shrink: 0;">关注</a></div>',
  },
  {
    id: 'follow-121',
    name: '实线外框+左右符号',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px; border: 2px solid #4a7dd4; border-radius: 10px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">✦ <span style="color: #4a7dd4;">点击关注</span> 发现更多好文 ✦</p></div>',
  },
  {
    id: 'follow-122',
    name: '虚线边框引导',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px; border: 1px dashed #4a7dd4; border-radius: 8px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #777;">🔍 干货不断，<span style="color: #4a7dd4;">欢迎关注</span></p></div>',
  },
  {
    id: 'follow-123',
    name: '点状边框+星星图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px; border: 2px dotted #cccccc; border-radius: 12px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">⭐ 星光相伴，<span style="color: #4a7dd4;">关注不缺席</span></p></div>',
  },
  {
    id: 'follow-124',
    name: '双边框叠加样式',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 6px; border: 1px solid #4a7dd4; border-radius: 10px;"><div style="padding: 12px; background: #fff; border-radius: 6px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #777;">📖 每日新知，等你来阅</p><p style="margin: 6px 0 0; font-size: 13px;"><span style="color: #4a7dd4;">一键关注</span></p></div></div>',
  },
  {
    id: 'follow-125',
    name: '上下波浪线分隔',
    category: 'follow',
    html: '<p style="text-align: center; color: #4a7dd4; margin: 0; font-size: 16px;">﹏﹏﹏﹏﹏﹏﹏﹏</p><p style="text-align: center; margin: 10px 0; font-size: 14px; color: #666;">💫 喜欢内容，记得 <span style="color: #4a7dd4;">关注</span></p><p style="text-align: center; color: #4a7dd4; margin: 0; font-size: 16px;">﹏﹏﹏﹏﹏﹏﹏﹏</p>',
  },
  {
    id: 'follow-126',
    name: '圆角粗边框+爱心',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; border: 3px solid #e74c3c; border-radius: 14px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">♥ 感恩相遇，<span style="color: #4a7dd4;">感谢关注</span> ♥</p></div>',
  },
  {
    id: 'follow-127',
    name: '单侧竖线装饰边框',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px 14px 14px 20px; border-left: 4px solid #4a7dd4; background: #f8f9fc; border-radius: 0 8px 8px 0; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">📌 优质内容持续更新</p><p style="margin: 4px 0 0; font-size: 13px; color: #888;"><span style="color: #4a7dd4;">点击关注</span> 第一时间接收</p></div>',
  },
  {
    id: 'follow-128',
    name: '四角符号装饰',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; border: 1px solid #e0e0e0; border-radius: 8px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #777;">❀ <span style="color: #4a7dd4;">关注账号</span> 共享美好时光 ❀</p></div>',
  },
  {
    id: 'follow-129',
    name: '阶梯边框+书本图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 15px; border: 1px solid #4a7dd4; border-radius: 4px 16px 4px 16px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">📚 以文会友，<span style="color: #4a7dd4;">欢迎驻足关注</span></p></div>',
  },
  {
    id: 'follow-130',
    name: '长虚线全包围边框',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px; border: 2px dashed #999; border-radius: 10px; text-align: center;"><p style="margin: 0; font-size: 13px; color: #777;">✨ 看完别走开，<span style="color: #4a7dd4;">点个关注再走哦</span></p></div>',
  },
  {
    id: 'follow-131',
    name: '双竖线包裹文字',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #666;">┃ 🎯 精选干货 · <span style="color: #4a7dd4;">关注收藏</span> ┃</p>',
  },
  {
    id: 'follow-132',
    name: '浅底细边框+相机图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; background: #f5f7fa; border: 1px solid #dcdfe6; border-radius: 8px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">📷 记录生活，分享乐趣</p><p style="margin: 5px 0 0; font-size: 13px;"><span style="color: #4a7dd4;">关注我，一起发现美好</span></p></div>',
  },
  {
    id: 'follow-133',
    name: '圆弧异型边框+喇叭图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px; border: 2px solid #4a7dd4; border-radius: 20px 4px 20px 4px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">📢 每日推送，<span style="color: #4a7dd4;">关注不错过</span></p></div>',
  },
  {
    id: 'follow-134',
    name: '圆点分割多行文案',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #777;">● ● ●</p><p style="text-align: center; margin: 8px 0; font-size: 14px; color: #666;">💡 内容实用，建议收藏</p><p style="text-align: center; margin: 8px 0; font-size: 14px;"><span style="color: #4a7dd4;">顺手点个关注，持续更新</span></p><p style="text-align: center; margin: 8px 0 0; font-size: 14px; color: #777;">● ● ●</p>',
  },
  {
    id: 'follow-135',
    name: '顶部三角装饰边框',
    category: 'follow',
    html: '<div style="margin: 20px 0; text-align: center;"><span style="color: #4a7dd4; font-size: 20px;">▼</span><div style="margin-top: -4px; padding: 14px; border: 1px solid #4a7dd4; border-radius: 8px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">🚀 成长之路，<span style="color: #4a7dd4;">一路相伴</span></p></div></div>',
  },
  {
    id: 'follow-136',
    name: '灰色磨砂边框+礼物图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; border: 1px solid #c9cdd4; border-radius: 10px; box-shadow: 0 1px 3px #eee; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">🎁 更多惊喜内容，<span style="color: #4a7dd4;">关注解锁</span></p></div>',
  },
  {
    id: 'follow-137',
    name: '方括号全装饰样式',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #777;">【 📝 好文推荐 | <span style="color: #4a7dd4;">欢迎关注</span> 】</p>',
  },
  {
    id: 'follow-138',
    name: '上下双横线+奖杯图标',
    category: 'follow',
    html: '<p style="text-align: center; margin: 0; color: #4a7dd4;">——————————</p><p style="text-align: center; margin: 10px 0; font-size: 14px; color: #666;">🏆 干货分享，<span style="color: #4a7dd4;">感谢支持与关注</span></p><p style="text-align: center; margin: 0; color: #4a7dd4;">——————————</p>',
  },
  {
    id: 'follow-139',
    name: '细边框圆角+雨伞图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px; border: 1px solid #888; border-radius: 16px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">☂️ 温柔文字，<span style="color: #4a7dd4;">陪你朝夕</span></p></div>',
  },
  {
    id: 'follow-140',
    name: '斜角分割边框',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 15px; border: 1px solid #4a7dd4; border-radius: 12px 2px 12px 2px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">🎪 趣味内容，每日上新</p><p style="margin: 4px 0 0; font-size: 13px; color: #888;"><span style="color: #4a7dd4;">关注即可第一时间查看</span></p></div>',
  },

  // ====================== 141-160 颜文字 + 萌系风格 + 二次元符号 ======================
  {
    id: 'follow-141',
    name: '颜文字萌系关注1',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #777;">(≧∇≦)ﾉ 看完啦？<span style="color: #4a7dd4;">点个关注再走吧~</span></p>',
  },
  {
    id: 'follow-142',
    name: '颜文字边框卡片',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; border: 1px dashed #f0b8c0; border-radius: 10px; background: #fff8fa; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">(๑•̀ㅂ•́)و✧ <span style="color: #4a7dd4;">关注我，快乐不打烊</span></p></div>',
  },
  {
    id: 'follow-143',
    name: '害羞颜文字+爱心',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #888;">(⁄ ⁄•⁄ω⁄•⁄ ⁄) 求求啦，给个 <span style="color: #4a7dd4;">关注</span> 吧♥</p>',
  },
  {
    id: 'follow-144',
    name: '元气颜文字+虚线框',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px; border: 2px dotted #7fb8f0; border-radius: 12px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">ヾ(≧▽≦)ゞ 每日更新，<span style="color: #4a7dd4;">关注集合啦</span></p></div>',
  },
  {
    id: 'follow-145',
    name: '犯困颜文字小字',
    category: 'follow',
    html: '<p style="text-align: center; margin: 18px 0; font-size: 13px; color: #999;">( ´-ω-)σ 码字不易，麻烦 <span style="color: #4a7dd4;">关注</span> 一下哦</p>',
  },
  {
    id: 'follow-146',
    name: '欢呼颜文字+粗边框',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; border: 2px solid #4a7dd4; border-radius: 8px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">ヽ(≧Д≦)ノ <span style="color: #4a7dd4;">关注同行，一起进步</span></p></div>',
  },
  {
    id: 'follow-147',
    name: '乖巧颜文字+花朵符号',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #777;">✿ (´･ω･`) ✿ 喜欢就 <span style="color: #4a7dd4;">关注</span> 停留片刻吧</p>',
  },
  {
    id: 'follow-148',
    name: '颜文字双层卡片',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 8px; border: 1px solid #e74c3c; border-radius: 10px;"><div style="padding: 12px; background: #fff; border-radius: 6px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">(๑˃̵ᴗ˂̵)و 海量内容等你来发掘</p><p style="margin: 5px 0 0; font-size: 13px;"><span style="color: #4a7dd4;">点击关注</span></p></div></div>',
  },
  {
    id: 'follow-149',
    name: '挥手颜文字+波浪线',
    category: 'follow',
    html: '<p style="text-align: center; color: #999;">﹏﹏﹏﹏</p><p style="text-align: center; margin: 8px 0; font-size: 14px; color: #777;">(｡･ω･)ﾉﾞ 拜拜，记得 <span style="color: #4a7dd4;">关注</span> 下次见</p><p style="text-align: center; color: #999;">﹏﹏﹏﹏</p>',
  },
  {
    id: 'follow-150',
    name: '星星颜文字点状边框',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px; border: 2px dotted #ffc8dd; border-radius: 14px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">☆(≧∀≦*)ﾉ <span style="color: #4a7dd4;">宝藏账号，值得关注</span></p></div>',
  },
  {
    id: 'follow-151',
    name: '无奈颜文字简约款',
    category: 'follow',
    html: '<p style="text-align: center; margin: 18px 0; font-size: 13px; color: #888;">(´・ω・`) 干货满满，别忘了 <span style="color: #4a7dd4;">关注</span> 收藏</p>',
  },
  {
    id: 'follow-152',
    name: '开心颜文字+左侧竖线',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px 14px 14px 18px; border-left: 3px solid #e74c3c; background: #fff5f5; border-radius: 0 8px 8px 0; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">(^o^)/~ 分享快乐，<span style="color: #4a7dd4;">欢迎关注</span></p></div>',
  },
  {
    id: 'follow-153',
    name: '捂脸颜文字趣味款',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #777;">(*/ω＼*) 偷偷说，<span style="color: #4a7dd4;">关注</span> 之后福利多多</p>',
  },
  {
    id: 'follow-154',
    name: '奔跑颜文字全边框',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 15px; border: 1px solid #4a7dd4; border-radius: 10px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">ヾ(´▽｀;)ゝ 追更不停，<span style="color: #4a7dd4;">关注走起</span></p></div>',
  },
  {
    id: 'follow-155',
    name: '小花符号+颜文字组合',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #888;">✽ (๑•̀ㅂ•́) ✽ <span style="color: #4a7dd4;">与美好不期而遇</span></p>',
  },
  {
    id: 'follow-156',
    name: '呆萌颜文字浅底卡片',
    category: 'follow',
    html: `<div style="margin: 20px 0; padding: 16px; background: #f0f8ff; border-radius: 8px; border: 1px solid #d0e4f7; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">(●'◡'●) 每天都有新内容，<span style="color: #4a7dd4;">等你关注</span></p></div>`,
  },
  {
    id: 'follow-157',
    name: '挥手告别颜文字',
    category: 'follow',
    html: '<p style="text-align: center; margin: 18px 0; font-size: 13px; color: #999;">(｡•́ω•̀｡) 本期结束，<span style="color: #4a7dd4;">关注</span> 我们下期再会</p>',
  },
  {
    id: 'follow-158',
    name: '闪电符号+元气颜文字',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px; border: 2px dashed #92b8f0; border-radius: 12px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">⚡ (≧∇≦)ﾉ 知识快充，<span style="color: #4a7dd4;">即刻关注</span></p></div>',
  },
  {
    id: 'follow-159',
    name: '括号包围颜文字',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #777;">「 (´･ᴗ･`) <span style="color: #4a7dd4;">用心创作，感谢关注</span> 」</p>',
  },
  {
    id: 'follow-160',
    name: '糖果色边框+开心颜文字',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 15px; border: 2px solid #f7b3c1; border-radius: 16px; background: #fff9fa; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">(๑>ᴗ<๑) 愿内容温暖你的每一天</p><p style="margin: 5px 0 0; font-size: 13px;"><span style="color: #4a7dd4;">记得点个关注哦</span></p></div>',
  },

  // ====================== 161-180 立体阴影边框 + 多图标组合 + 潮流符号 ======================
  {
    id: 'follow-161',
    name: '立体阴影卡片+火箭图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 18px; background: #fff; border-radius: 10px; border: 1px solid #eee; box-shadow: 0 2px 8px rgba(74,125,212,0.15); text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">🚀 进阶学习，<span style="color: #4a7dd4;">关注同行</span></p></div>',
  },
  {
    id: 'follow-162',
    name: '双层阴影边框+音乐图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 10px; border: 1px solid #4a7dd4; border-radius: 10px; box-shadow: 3px 3px 0 #e8edf7;"><div style="padding: 12px; background: #fff; border-radius: 6px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">🎵 聆听美好，<span style="color: #4a7dd4;">欢迎关注</span></p></div></div>',
  },
  {
    id: 'follow-163',
    name: '多图标组合+细边框',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; border: 1px solid #dcdfe6; border-radius: 8px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">👍 📚 💡 点赞 · 收藏 · <span style="color: #4a7dd4;">关注</span></p></div>',
  },
  {
    id: 'follow-164',
    name: '斜纹视觉边框+罗盘图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; border: 2px solid #4a7dd4; border-radius: 8px; background: linear-gradient(#ffffff, #f7f9fd); text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">🧭 探索新知，<span style="color: #4a7dd4;">关注出发</span></p></div>',
  },
  {
    id: 'follow-165',
    name: '四角圆点装饰+咖啡图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; border: 1px solid #888; border-radius: 10px; position: relative; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">☕ 闲暇时光，好文相伴</p><p style="margin: 5px 0 0; font-size: 13px;"><span style="color: #4a7dd4;">点击关注，每日品读</span></p></div>',
  },
  {
    id: 'follow-166',
    name: '箭头环绕装饰边框',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px; border: 1px dashed #4a7dd4; border-radius: 12px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">➤ <span style="color: #4a7dd4;">关注</span> 解锁全部精彩 ➤</p></div>',
  },
  {
    id: 'follow-167',
    name: '枫叶图标+国风细边框',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; border: 1px solid #c8a88a; border-radius: 8px; background: #fdfaf5; text-align: center;"><p style="margin: 0; font-size: 14px; color: #555;">🍁 品读风雅，<span style="color: #4a7dd4;">静候关注</span></p></div>',
  },
  {
    id: 'follow-168',
    name: '云朵底纹+多层图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; background: #f5f9ff; border-radius: 10px; border: 1px solid #d0dff3; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">☁️ 🌤️ ☀️ 一路相伴，<span style="color: #4a7dd4;">感谢关注</span></p></div>',
  },
  {
    id: 'follow-169',
    name: '方块符号包围文案',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #777;">■ ■ <span style="color: #4a7dd4;">优质内容</span> ■ ■</p><p style="text-align: center; margin: 6px 0; font-size: 13px; color: #888;">持续更新，欢迎关注</p>',
  },
  {
    id: 'follow-170',
    name: '加厚边框+钻石图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 15px; border: 3px solid #4a7dd4; border-radius: 8px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">💎 精品内容，<span style="color: #4a7dd4;">值得你关注</span></p></div>',
  },
  {
    id: 'follow-171',
    name: '分割线+多表情组合',
    category: 'follow',
    html: '<p style="text-align: center; margin: 0; color: #ccc;">————————————</p><p style="text-align: center; margin: 10px 0; font-size: 14px; color: #777;">😉 📖 ✨ 看完记得 <span style="color: #4a7dd4;">关注</span> 哦</p><p style="text-align: center; margin: 0; color: #ccc;">————————————</p>',
  },
  {
    id: 'follow-172',
    name: '凹凸造型边框+绿植图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px; border: 2px solid #73b884; border-radius: 6px 18px 6px 18px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">🌿 治愈日常，<span style="color: #4a7dd4;">关注相伴</span></p></div>',
  },
  {
    id: 'follow-173',
    name: '渐变底色+简约边框',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; background: linear-gradient(135deg,#f0f6ff,#e8f0ff); border: 1px solid #c6d8f2; border-radius: 10px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #444;">💌 每日推送，<span style="color: #4a7dd4;">关注不错漏</span></p></div>',
  },
  {
    id: 'follow-174',
    name: '爱心边框组合样式',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 14px; border: 2px solid #e74c3c; border-radius: 12px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">♥ 用心分享，<span style="color: #4a7dd4;">感恩关注</span> ♥</p></div>',
  },
  {
    id: 'follow-175',
    name: '齿轮图标+工业风细边框',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 15px; border: 1px solid #666; border-radius: 4px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">⚙️ 技巧干货，<span style="color: #4a7dd4;">持续输出</span></p><p style="margin: 4px 0 0; font-size: 13px; color: #888;">点击关注，一起学习</p></div>',
  },
  {
    id: 'follow-176',
    name: '圆环符号+居中文案',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #777;">◎ <span style="color: #4a7dd4;">专注内容 · 用心分享</span> ◎</p>',
  },
  {
    id: 'follow-177',
    name: '毛边质感边框+星球图标',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 16px; border: 1px solid #b8b8b8; border-radius: 8px; box-shadow: inset 0 0 4px #f0f0f0; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">🌍 眼界开阔，<span style="color: #4a7dd4;">关注同行</span></p></div>',
  },
  {
    id: 'follow-178',
    name: '多段符号分割+表情',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #777;">┈ ✧ 📝 ✧ ┈</p><p style="text-align: center; margin: 8px 0; font-size: 14px;"><span style="color: #4a7dd4;">喜欢就关注，下期更精彩</span></p>',
  },
  {
    id: 'follow-179',
    name: '圆角超大边框+礼物盒',
    category: 'follow',
    html: '<div style="margin: 20px 0; padding: 18px; border: 2px solid #4a7dd4; border-radius: 20px; text-align: center;"><p style="margin: 0; font-size: 14px; color: #666;">🎁 超多福利与好文，<span style="color: #4a7dd4;">一键关注领取</span></p></div>',
  },
  {
    id: 'follow-180',
    name: '左右箭头全包围样式',
    category: 'follow',
    html: '<p style="text-align: center; margin: 20px 0; font-size: 14px; color: #666;">◀◀◀ <span style="color: #4a7dd4;">点击关注</span> ▶▶▶</p>',
  }
]
