import type { TemplateItem } from '../types'

export const id = 'footer'
export const name = '底部提示'
export const icon = '👣'

export const templates: TemplateItem[] = [
  {
    id: 'footer-1',
    name: '阅读原文',
    category: 'footer',
    html: '<div style="margin: 25px 0 15px; padding: 16px 0; border-top: 1px solid #e0e2e8; text-align: center;"><p style="margin: 0 0 6px; font-size: 14px; color: #333; font-weight: bold;">📖 阅读原文</p><p style="margin: 0;"><a style="color: #4a7dd4; text-decoration: none; font-size: 13px;">查看完整内容 →</a></p></div>',
  },
  {
    id: 'footer-2',
    name: '推荐阅读',
    category: 'footer',
    html: '<div style="margin: 25px 0 15px; padding: 18px; background: #f5f7fa; border-radius: 8px;"><p style="margin: 0 0 10px; font-size: 14px; font-weight: bold; color: #333;">📚 推荐阅读</p><p style="margin: 0 0 6px;"><a style="color: #4a7dd4; text-decoration: none; font-size: 13px;">▶ 上一篇精彩文章</a></p><p style="margin: 0;"><a style="color: #4a7dd4; text-decoration: none; font-size: 13px;">▶ 另一篇相关推荐</a></p></div>',
  },
  {
    id: 'footer-3',
    name: '互动引导',
    category: 'footer',
    html: '<div style="margin: 25px 0 15px; text-align: center;"><p style="margin: 0 0 8px; font-size: 14px; font-weight: bold; color: #333;">💬 一起来讨论</p><p style="margin: 0 0 12px; font-size: 13px; color: #888;">欢迎在评论区分享你的看法</p><div style="display: flex; justify-content: center; gap: 16px;"><span style="padding: 6px 18px; border: 1px solid #e0e2e8; border-radius: 16px; font-size: 13px; color: #666; cursor: pointer;">点赞 👍</span><span style="padding: 6px 18px; border: 1px solid #e0e2e8; border-radius: 16px; font-size: 13px; color: #666; cursor: pointer;">在看 ❤</span><span style="padding: 6px 18px; border: 1px solid #e0e2e8; border-radius: 16px; font-size: 13px; color: #666; cursor: pointer;">分享 ↗</span></div></div>',
  },
  {
    id: 'footer-4',
    name: '极简虚线分隔',
    category: 'footer',
    html: '<div style="margin: 30px 0 20px; border-top: 1px dashed #ccc; text-align: center; padding-top: 20px;"><span style="font-size: 12px; color: #999;">·  END  ·</span></div>',
  },
  {
    id: 'footer-5',
    name: '双行小字备注',
    category: 'footer',
    html: '<div style="margin: 20px 0 10px; text-align: center; font-size: 11px; color: #aaa;"><p style="margin: 0 0 4px;">内容仅供参考，不构成任何建议</p><p style="margin: 0;">© 2025 你的品牌</p></div>',
  },
  {
    id: 'footer-6',
    name: '左侧二维码引导',
    category: 'footer',
    html: '<div style="margin: 25px 0; display: flex; align-items: center; gap: 16px; background: #fafbfc; padding: 12px; border-radius: 12px;"><div style="width: 48px; height: 48px; background: #ddd; border-radius: 8px; text-align: center; line-height: 48px; font-size: 24px;">📱</div><div><p style="margin: 0 0 4px; font-weight: bold;">扫码关注公众号</p><p style="margin: 0; font-size: 12px; color: #666;">获取更多干货</p></div></div>',
  },
  {
    id: 'footer-7',
    name: '右侧按钮引导',
    category: 'footer',
    html: '<div style="margin: 25px 0; display: flex; justify-content: space-between; align-items: center; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 14px 20px; border-radius: 40px; color: white;"><span style="font-weight: bold;">🎁 限时福利</span><span style="background: rgba(255,255,255,0.2); padding: 6px 16px; border-radius: 30px; font-size: 13px;">立即领取 →</span></div>',
  },
  {
    id: 'footer-8',
    name: '纯文本链接列表',
    category: 'footer',
    html: '<div style="margin: 30px 0 15px; text-align: center; font-size: 12px;"><a href="#" style="color: #666; margin: 0 8px; text-decoration: none;">关于我们</a><span>|</span><a href="#" style="color: #666; margin: 0 8px; text-decoration: none;">隐私政策</a><span>|</span><a href="#" style="color: #666; margin: 0 8px; text-decoration: none;">联系我们</a></div>',
  },
  {
    id: 'footer-9',
    name: '浅灰卡片+社交图标',
    category: 'footer',
    html: '<div style="margin: 25px 0; padding: 20px; background: #f8f9fa; border-radius: 16px; text-align: center;"><div style="display: flex; justify-content: center; gap: 24px; margin-bottom: 12px;"><span style="font-size: 20px;">🐦</span><span style="font-size: 20px;">📘</span><span style="font-size: 20px;">📷</span><span style="font-size: 20px;">💼</span></div><p style="margin: 0; font-size: 12px; color: #888;">关注我们的社交账号</p></div>',
  },
  {
    id: 'footer-10',
    name: '暖橙订阅',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #ff9a3c; border-radius: 20px; padding: 20px; text-align: center; color: white;"><p style="margin: 0 0 8px; font-weight: bold;">🔥 订阅更新</p><p style="margin: 0 0 16px; font-size: 13px;">第一时间收到新内容</p></div>',
  },
  {
    id: 'footer-11',
    name: '薄荷绿提示',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #d4f1f9; border-left: 6px solid #1abc9c; padding: 14px; border-radius: 8px;"><p style="margin: 0; font-size: 13px; color: #2c3e50;">💡 小提示：点击右下角可切换深色模式</p></div>',
  },
  {
    id: 'footer-12',
    name: '星空渐变',
    category: 'footer',
    html: '<div style="margin: 30px 0 20px; background: linear-gradient(120deg, #0f2027, #203a43, #2c5364); padding: 28px 20px; border-radius: 24px; text-align: center; color: white;"><p style="margin: 0 0 8px; font-size: 18px; letter-spacing: 2px;">✨ 探索更多 ✨</p><p style="margin: 0; font-size: 12px; opacity: 0.7;">每日更新，不见不散</p></div>',
  },
  {
    id: 'footer-13',
    name: '霓虹边框',
    category: 'footer',
    html: '<div style="margin: 25px 0; padding: 16px; border: 2px solid #ff00cc; border-radius: 12px; text-align: center; background: #fff0f9;"><span style="color: #ff00cc; font-weight: bold;">💖 关注我们，获取更多灵感 💖</span></div>',
  },
  {
    id: 'footer-14',
    name: '半透明毛玻璃',
    category: 'footer',
    html: '<div style="margin: 25px 0; backdrop-filter: blur(10px); background: rgba(255,255,255,0.6); border-radius: 20px; padding: 20px; text-align: center; box-shadow: 0 4px 12px rgba(0,0,0,0.05);"><p style="margin: 0 0 6px;">📮 订阅周刊</p></div>',
  },
  {
    id: 'footer-15',
    name: '双栏信息',
    category: 'footer',
    html: '<div style="margin: 25px 0; display: flex; justify-content: space-between; flex-wrap: wrap; gap: 16px; background: #f2f2f2; padding: 20px; border-radius: 16px;"><div><p style="margin: 0 0 6px; font-weight: bold;">关于</p><p style="margin: 0; font-size: 12px;">团队介绍</p><p style="margin: 0; font-size: 12px;">加入我们</p></div><div><p style="margin: 0 0 6px; font-weight: bold;">支持</p><p style="margin: 0; font-size: 12px;">帮助中心</p><p style="margin: 0; font-size: 12px;">反馈建议</p></div><div><p style="margin: 0 0 6px; font-weight: bold;">社交</p><p style="margin: 0; font-size: 12px;">微博 / 公众号</p></div></div>',
  },
  {
    id: 'footer-16',
    name: '表情包反馈',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center;"><p style="margin: 0 0 10px; font-size: 13px; color: #555;">这篇文章对你有帮助吗？</p><div style="display: flex; justify-content: center; gap: 24px;"><span style="font-size: 28px; cursor: default;">😊</span><span style="font-size: 28px; cursor: default;">😐</span><span style="font-size: 28px; cursor: default;">😞</span></div></div>',
  },
  {
    id: 'footer-17',
    name: '横向推荐文章',
    category: 'footer',
    html: '<div style="margin: 25px 0;"><p style="margin: 0 0 12px; font-weight: bold;">📌 猜你喜欢</p><div style="display: flex; gap: 12px; overflow-x: auto;"><div style="min-width: 100px; background: #f3f4f6; border-radius: 12px; padding: 12px; text-align: center;"><span>📘</span><p style="margin: 6px 0 0; font-size: 12px;">文章A</p></div><div style="min-width: 100px; background: #f3f4f6; border-radius: 12px; padding: 12px; text-align: center;"><span>📙</span><p style="margin: 6px 0 0; font-size: 12px;">文章B</p></div><div style="min-width: 100px; background: #f3f4f6; border-radius: 12px; padding: 12px; text-align: center;"><span>📕</span><p style="margin: 6px 0 0; font-size: 12px;">文章C</p></div></div></div>',
  },
  {
    id: 'footer-18',
    name: '礼物抽奖',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #fef9e3; border-radius: 20px; padding: 20px; text-align: center; border: 1px dashed #f5b042;"><p style="margin: 0 0 6px; font-size: 22px;">🎁</p><p style="margin: 0 0 6px; font-weight: bold;">参与抽奖</p><p style="margin: 0 0 12px; font-size: 12px;">评论点赞抽取3位送小礼品</p><span style="background: #f5b042; padding: 6px 20px; border-radius: 40px; color: black; font-size: 13px;">立即参与</span></div>',
  },
  {
    id: 'footer-19',
    name: '作者介绍',
    category: 'footer',
    html: '<div style="margin: 25px 0; display: flex; gap: 16px; align-items: center; background: #fff; border: 1px solid #eee; border-radius: 20px; padding: 16px;"><div style="width: 48px; height: 48px; background: #8b5cf6; border-radius: 50%; text-align: center; line-height: 48px; color: white;">👤</div><div><p style="margin: 0 0 4px; font-weight: bold;">张三</p><p style="margin: 0; font-size: 12px; color: #666;">前端开发工程师，热爱分享技术</p></div></div>',
  },
  {
    id: 'footer-20',
    name: '引用名言',
    category: 'footer',
    html: '<div style="margin: 25px 0; border-left: 4px solid #eab308; background: #fffbeb; padding: 12px 16px; border-radius: 12px;"><p style="margin: 0 0 4px; font-style: italic; font-size: 13px;">“保持好奇，终身学习”</p><p style="margin: 0; text-align: right; font-size: 12px; color: #a16207;">—— 与你共勉</p></div>',
  },
  {
    id: 'footer-21',
    name: '统计卡片',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: linear-gradient(145deg, #ffffff, #f5f7fa); border-radius: 20px; padding: 18px; text-align: center; box-shadow: 0 4px 12px rgba(0,0,0,0.05);"><div style="display: flex; justify-content: space-around;"><div><p style="margin: 0; font-size: 20px; font-weight: bold;">1.2k</p><p style="margin: 0; font-size: 11px; color: #888;">阅读量</p></div><div><p style="margin: 0; font-size: 20px; font-weight: bold;">48</p><p style="margin: 0; font-size: 11px; color: #888;">点赞</p></div><div><p style="margin: 0; font-size: 20px; font-weight: bold;">12</p><p style="margin: 0; font-size: 11px; color: #888;">评论</p></div></div></div>',
  },
  {
    id: 'footer-22',
    name: '纯文字鼓励',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; font-size: 12px; color: #888;">感谢阅读，祝你今天愉快 🌈</div>',
  },
  {
    id: 'footer-23',
    name: '带图标的版权',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; font-size: 12px; color: #aaa;"><span>© 2025 YourBrand</span><span style="margin: 0 8px">·</span><span>✨ 保留一切权利</span></div>',
  },
  {
    id: 'footer-24',
    name: '折叠面板风格',
    category: 'footer',
    html: '<div style="margin: 25px 0; border: 1px solid #e2e8f0; border-radius: 16px; overflow: hidden;"><div style="background: #f8fafc; padding: 12px 16px; font-weight: bold;">📌 更多资源</div><div style="padding: 12px 16px; background: white;"><p style="margin: 0 0 6px;"><a style="color: #3b82f6; text-decoration: none;">电子书下载</a></p><p style="margin: 0;"><a style="color: #3b82f6; text-decoration: none;">视频课程</a></p></div></div>',
  },
  {
    id: 'footer-25',
    name: '气泡对话',
    category: 'footer',
    html: '<div style="margin: 25px 0; display: flex; justify-content: center;"><div style="background: #e9f5ff; border-radius: 20px 20px 20px 4px; padding: 12px 20px; max-width: 80%;"><p style="margin: 0; font-size: 13px;">💬 有什么想说的？评论区等你~</p></div></div>',
  },
  {
    id: 'footer-26',
    name: '节日氛围',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #fef2f2; border-radius: 40px; padding: 12px 20px; text-align: center; color: #b91c1c;">🎄 圣诞快乐 · 新年将至 🎄</div>',
  },
  {
    id: 'footer-27',
    name: '打卡签到',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; background: #ecfdf5; border-radius: 28px; padding: 16px;"><span style="background: #10b981; color: black; padding: 6px 20px; border-radius: 30px;">✅ 打卡签到</span><p style="margin: 10px 0 0; font-size: 12px;">连续打卡7天有惊喜</p></div>',
  },
  {
    id: 'footer-28',
    name: '暗黑模式适配',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #1e1e2f; border-radius: 20px; padding: 20px; text-align: center; color: #cdcdff;"><p style="margin: 0 0 6px;">🌙 暗色模式已就绪</p><p style="margin: 0; font-size: 12px; opacity: 0.7;">保护眼睛，夜间阅读更舒适</p></div>',
  },
  {
    id: 'footer-29',
    name: '轮播提示',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #fef9c3; border-radius: 12px; padding: 10px; text-align: center; font-size: 13px;">👉 滑动屏幕查看更多内容 👈</div>',
  },
  {
    id: 'footer-30',
    name: '表情评分',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #f3e8ff; border-radius: 28px; padding: 14px; text-align: center;"><p style="margin: 0 0 8px;">⭐ 评分 ⭐</p><div style="font-size: 22px; letter-spacing: 4px;">★★★★☆</div></div>',
  },
  {
    id: 'footer-31',
    name: '软广植入',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: linear-gradient(90deg, #f9f9ff, #e9e9ff); border-radius: 24px; padding: 14px 20px; display: flex; align-items: center; justify-content: space-between;"><span style="font-weight: bold;">✨ 赞助商 ✨</span><span style="font-size: 12px;">XX品牌 · 让创作更简单</span></div>',
  },
  {
    id: 'footer-32',
    name: '诗词结尾',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; font-family: serif; color: #444;"><p style="margin: 0 0 6px;">“长风破浪会有时”</p><p style="margin: 0; font-size: 12px;">—— 李白</p></div>',
  },
  {
    id: 'footer-33',
    name: '加载更多按钮',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center;"><span style="display: inline-block; background: #f1f5f9; padding: 10px 24px; border-radius: 30px; font-size: 13px; color: #475569;">加载更多文章 ↓</span></div>',
  },
  {
    id: 'footer-34',
    name: '星级推荐',
    category: 'footer',
    html: '<div style="margin: 25px 0; display: flex; align-items: center; justify-content: center; gap: 8px;"><span>🔥 热门推荐</span><span>★★★★★</span><span>(128)</span></div>',
  },
  {
    id: 'footer-35',
    name: '手绘风格',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; font-family: \'Comic Sans MS\', cursive; border: 2px solid #facc15; border-radius: 60px 20px 60px 20px; padding: 12px; background: #fff9e6;">✨ 觉得不错就点个赞再走呗 ✨</div>',
  },
  {
    id: 'footer-36',
    name: '倒计时促销',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #fee2e2; border-radius: 16px; padding: 14px; text-align: center;"><p style="margin: 0 0 6px;">⏰ 限时优惠 还剩</p><p style="margin: 0; font-size: 20px; font-weight: bold;">02:15:33</p></div>',
  },
  {
    id: 'footer-37',
    name: '免责声明',
    category: 'footer',
    html: '<div style="margin: 25px 0; font-size: 10px; color: #aaa; text-align: center; line-height: 1.4;">免责声明：本文仅代表作者观点，不代表平台立场。如有疑问，请联系我们。</div>',
  },
  {
    id: 'footer-38',
    name: '金色奖章',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: linear-gradient(135deg, #f6d5a3, #f0b27a); padding: 16px; border-radius: 16px; text-align: center; color: #5e2a00;"><span style="font-size: 28px;">🏆</span><p style="margin: 6px 0 0;">本周热门文章 Top 3</p></div>',
  },
  {
    id: 'footer-39',
    name: '扩展阅读',
    category: 'footer',
    html: '<div style="margin: 25px 0;"><details style="border: 1px solid #e2e8f0; border-radius: 12px; padding: 12px;"><summary style="font-weight: bold; cursor: pointer;">🔍 扩展阅读</summary><p style="margin: 12px 0 0; font-size: 13px;"><a href="#" style="color: #2563eb;">相关论文解读</a><br><a href="#" style="color: #2563eb;">深度分析报告</a></p></details></div>',
  },
  {
    id: 'footer-40',
    name: '赞赏作者',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center;"><p style="margin: 0 0 10px;">👍 如果对你有帮助，可以赞赏作者</p><div style="background: #facc15; display: inline-block; padding: 8px 24px; border-radius: 40px; font-weight: bold;">赏一杯咖啡 ☕</div></div>',
  },
  {
    id: 'footer-41',
    name: '代码风格',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #1f2937; color: #9ca3af; padding: 16px; border-radius: 12px; font-family: monospace; font-size: 11px;"><pre style="margin: 0; white-space: pre-wrap;">// 感谢阅读，保持好奇<br>console.log("See you next time!");</pre></div>',
  },
  {
    id: 'footer-42',
    name: '终端风格',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #0a0c10; border-radius: 12px; padding: 12px; color: #0f0; font-family: monospace;"><span>$</span> <span style="color: #fff;">感谢阅读，欢迎反馈</span><br><span>$</span> <span style="color: #0f0;">_</span></div>',
  },
  {
    id: 'footer-43',
    name: '极简日期',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; font-size: 11px; color: #bbb;">2026 · 05 · 28</div>',
  },
  {
    id: 'footer-44',
    name: '问答引导',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center;"><p style="margin: 0 0 8px;">🤔 还有疑问？</p><span style="background: #e0e7ff; padding: 6px 20px; border-radius: 30px; color: #4338ca;">前往问答区</span></div>',
  },
  {
    id: 'footer-45',
    name: 'RSS订阅',
    category: 'footer',
    html: '<div style="margin: 25px 0; display: flex; justify-content: center; gap: 20px;"><span>📡 RSS</span><span>📧 邮件订阅</span><span>🔔 通知</span></div>',
  },
  {
    id: 'footer-46',
    name: '地图引导',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #ecfdf5; border-radius: 20px; padding: 14px; display: flex; align-items: center; gap: 10px;"><span>📍</span><span style="flex:1">下一站：React 性能优化</span><span>→</span></div>',
  },
  {
    id: 'footer-47',
    name: '社交关注条',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #ffffff; border-radius: 50px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); padding: 8px 16px; display: flex; justify-content: space-between;"><span>🐦 Twitter</span><span>📘 FB</span><span>📸 IG</span><span>🎵 TikTok</span></div>',
  },
  {
    id: 'footer-48',
    name: '彩虹渐变',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: linear-gradient(90deg, #ff9a9e, #fad0c4, #fad0c4, #ffdde1); padding: 12px; text-align: center; border-radius: 40px; color: #fff;">🌈 生活明朗，万物可爱 🌈</div>',
  },
  {
    id: 'footer-49',
    name: '测试版提示',
    category: 'footer',
    html: '<div style="margin: 25px 0; border: 2px solid #f97316; background: #fff7ed; padding: 10px; text-align: center; border-radius: 12px;"><span style="color: #ea580c;">⚠️ 测试版内容，仅供参考</span></div>',
  },
  {
    id: 'footer-50',
    name: '评论入口',
    category: 'footer',
    html: '<div style="margin: 25px 0; display: flex; justify-content: space-between; align-items: center; background: #f1f5f9; padding: 12px 20px; border-radius: 40px;"><span>💬 参与讨论</span><span>查看全部评论 →</span></div>',
  },
  {
    id: 'footer-51',
    name: '点赞小手',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center;"><span style="background: #f1f5f9; padding: 8px 24px; border-radius: 30px; display: inline-flex; align-items: center; gap: 8px;">👍 有帮助 <span style="background: #e2e8f0; border-radius: 20px; padding: 2px 8px;">32</span></span></div>',
  },
  {
    id: 'footer-52',
    name: '分享赚积分',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #fef2f2; border-radius: 16px; padding: 12px; text-align: center;"><p style="margin: 0;">🎁 分享文章可得20积分</p><span style="background: #dc2626; color: black; padding: 4px 16px; border-radius: 20px; display: inline-block; margin-top: 8px;">立即分享</span></div>',
  },
  {
    id: 'footer-53',
    name: '时钟',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; font-family: monospace; font-size: 24px; color: #334155;">12:34</div>',
  },
  {
    id: 'footer-54',
    name: '简单分割加装饰',
    category: 'footer',
    html: '<div style="margin: 30px 0 15px; text-align: center;"><span style="display: inline-block; width: 30px; height: 1px; background: #ccc; vertical-align: middle;"></span><span style="margin: 0 12px; font-size: 12px; color: #999;">⋆｡°✩</span><span style="display: inline-block; width: 30px; height: 1px; background: #ccc; vertical-align: middle;"></span></div>',
  },
  {
    id: 'footer-55',
    name: '播客推荐',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #1e293b; border-radius: 20px; padding: 16px; color: white; display: flex; gap: 12px;"><span>🎙️</span><div><p style="margin: 0; font-weight: bold;">收听本期播客</p><p style="margin: 0; font-size: 12px;">Apple Podcasts | Spotify</p></div></div>',
  },
  {
    id: 'footer-56',
    name: '一键三连',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center;"><div style="display: flex; justify-content: center; gap: 24px;"><span>👍 点赞</span><span>📢 转发</span><span>⭐ 收藏</span></div></div>',
  },
  {
    id: 'footer-57',
    name: '漫画结尾',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center;"><span style="font-size: 48px;">🐱</span><p style="margin: 4px 0 0;">“喵~ 下次再见”</p></div>',
  },
  {
    id: 'footer-58',
    name: '波浪纹',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; font-size: 18px; color: #ccc;">~~~~~~~~~~</div>',
  },
  {
    id: 'footer-59',
    name: '打卡日历',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #f1f5f9; border-radius: 20px; padding: 12px; text-align: center;"><p style="margin: 0 0 6px;">📅 今日已打卡</p><div style="display: flex; justify-content: center; gap: 4px;"><span>✅</span><span>✅</span><span>✅</span><span>⬜</span><span>⬜</span></div></div>',
  },
  {
    id: 'footer-60',
    name: '随机一句',
    category: 'footer',
    html: '<div style="margin: 25px 0; font-style: italic; text-align: center; color: #64748b;">“种一棵树最好的时间是十年前，其次是现在。”</div>',
  },
  {
    id: 'footer-61',
    name: '双色按钮',
    category: 'footer',
    html: '<div style="margin: 25px 0; display: flex; gap: 12px;"><div style="flex:1; text-align: center; background: #3b82f6; padding: 10px; border-radius: 12px; color: white;">👍 有用</div><div style="flex:1; text-align: center; background: #e2e8f0; padding: 10px; border-radius: 12px; color: #334155;">😞 一般</div></div>',
  },
  {
    id: 'footer-62',
    name: '翻转卡片提示',
    category: 'footer',
    html: '<div style="margin: 25px 0; perspective: 1000px;"><div style="background: #cbd5e1; padding: 20px; text-align: center; border-radius: 12px; transform: rotateX(2deg);">✨ 双击屏幕有惊喜 ✨</div></div>',
  },
  {
    id: 'footer-63',
    name: '地图脚印',
    category: 'footer',
    html: '<div style="margin: 25px 0; display: flex; justify-content: center; gap: 8px;"><span>🐾</span><span>🐾</span><span>🐾</span><span>🏁</span></div>',
  },
  {
    id: 'footer-64',
    name: '夜间模式提醒',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #2d2d3f; color: #cbd5e1; border-radius: 16px; padding: 12px; text-align: center;">🌙 夜间模式已开启，可手动关闭</div>',
  },
  {
    id: 'footer-65',
    name: '版本号',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; font-size: 10px; color: #aaa;">v2.4.0 · 最后更新: 2026-05</div>',
  },
  {
    id: 'footer-66',
    name: '隐藏彩蛋',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; color: #cbd5e1; font-size: 12px;">··· 此处有一个小彩蛋 ···</div>',
  },
  {
    id: 'footer-67',
    name: '动效文字',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; animation: fade 2s infinite; font-weight: bold;">✨ 感谢阅读，共同成长 ✨</div><style>@keyframes fade{0%{opacity:0.4;}50%{opacity:1;}100%{opacity:0.4;}}</style>',
  },
  {
    id: 'footer-68',
    name: '星轨',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; letter-spacing: 4px;">*  ✦  ⋆  ✧  ✦  *</div>',
  },
  {
    id: 'footer-69',
    name: '优惠券',
    category: 'footer',
    html: '<div style="margin: 25px 0; border: 2px dashed #fbbf24; border-radius: 16px; padding: 16px; text-align: center; background: #fffbeb;"><span style="font-size: 20px;">🎟️</span><p style="margin: 4px 0;">新人优惠券 · 满100减20</p><span style="background: #f59e0b; padding: 4px 20px; border-radius: 30px; display: inline-block;">领取</span></div>',
  },
  {
    id: 'footer-70',
    name: '九宫格',
    category: 'footer',
    html: '<div style="margin: 25px 0; display: grid; grid-template-columns: repeat(3,1fr); gap: 8px; text-align: center;"><div>🏠</div><div>📞</div><div>✉️</div><div>📷</div><div>🎥</div><div>🎧</div><div>💡</div><div>🔧</div><div>⚙️</div></div>',
  },
  {
    id: 'footer-71',
    name: '多语言切换',
    category: 'footer',
    html: '<div style="margin: 25px 0; text-align: center; font-size: 12px;"><span style="margin: 0 8px;">中文</span><span>|</span><span style="margin: 0 8px;">English</span><span>|</span><span style="margin: 0 8px;">日本語</span></div>',
  },
  {
    id: 'footer-72',
    name: '法律声明',
    category: 'footer',
    html: '<div style="margin: 25px 0; font-size: 10px; color: #aaa; text-align: center;">本网站内容受版权保护，未经许可不得转载。</div>',
  },
  {
    id: 'footer-73',
    name: '树洞',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #e6f7f0; border-radius: 30px; padding: 14px; text-align: center;">🌳 欢迎在树下留言分享你的故事</div>',
  },
  {
    id: 'footer-74',
    name: '快捷工具',
    category: 'footer',
    html: '<div style="margin: 25px 0; display: flex; justify-content: center; gap: 12px;"><span>🔍 搜索</span><span>📑 目录</span><span>🔖 书签</span></div>',
  },
  {
    id: 'footer-75',
    name: '跑马灯',
    category: 'footer',
    html: '<div style="margin: 25px 0; background: #fef9c3; overflow: hidden; white-space: nowrap; padding: 8px;"><marquee style="display: inline-block;">🔥 限时活动！评论区抽奖送会员 🔥</marquee></div>',
  },
  {
    id: 'footer-76',
    name: '手风琴FAQ',
    category: 'footer',
    html: '<div style="margin: 25px 0;"><details><summary style="font-weight: bold;">❓ 常见问题</summary><p style="margin: 8px 0 0;">如何购买？如何退款？更多问题请联系客服。</p></details></div>',
  },
  {
    id: 'footer-77',
    name: '封底图片占位',
    category: 'footer',
    html: '<div style="margin: 25px 0; height: 80px; background: linear-gradient(145deg, #cbd5e1, #94a3b8); border-radius: 24px; display: flex; align-items: center; justify-content: center; color: white;">✨ 广告位 ✨</div>',
  },
];
